#include <windows.h>
#include <stdio.h>

HINSTANCE mHinst = 0, mHinstDLL = 0;
UINT_PTR mProcs[727] = {0};
LPCSTR mImportNames[] = {"AbortDoc", "AbortPath", "AddFontMemResourceEx", "AddFontResourceA", "AddFontResourceExA", "AddFontResourceExW", "AddFontResourceTracking", "AddFontResourceW", "AngleArc", "AnimatePalette", "AnyLinkedFonts", "Arc", "ArcTo", "BRUSHOBJ_hGetColorTransform", "BRUSHOBJ_pvAllocRbrush", "BRUSHOBJ_pvGetRbrush", "BRUSHOBJ_ulGetBrushColor", "BeginGdiRendering", "BeginPath", "BitBlt", "CLIPOBJ_bEnum", "CLIPOBJ_cEnumStart", "CLIPOBJ_ppoGetPath", "CancelDC", "CheckColorsInGamut", "ChoosePixelFormat", "Chord", "ClearBitmapAttributes", "ClearBrushAttributes", "CloseEnhMetaFile", "CloseFigure", "CloseMetaFile", "ColorCorrectPalette", "ColorMatchToTarget", "CombineRgn", "CombineTransform", "ConfigureOPMProtectedOutput", "CopyEnhMetaFileA", "CopyEnhMetaFileW", "CopyMetaFileA", "CopyMetaFileW", "CreateBitmap", "CreateBitmapFromDxSurface", "CreateBitmapIndirect", "CreateBrushIndirect", "CreateColorSpaceA", "CreateColorSpaceW", "CreateCompatibleBitmap", "CreateCompatibleDC", "CreateDCA", "CreateDCW", "CreateDIBPatternBrush", "CreateDIBPatternBrushPt", "CreateDIBSection", "CreateDIBitmap", "CreateDiscardableBitmap", "CreateEllipticRgn", "CreateEllipticRgnIndirect", "CreateEnhMetaFileA", "CreateEnhMetaFileW", "CreateFontA", "CreateFontIndirectA", "CreateFontIndirectExA", "CreateFontIndirectExW", "CreateFontIndirectW", "CreateFontW", "CreateHalftonePalette", "CreateHatchBrush", "CreateICA", "CreateICW", "CreateMetaFileA", "CreateMetaFileW", "CreateOPMProtectedOutputs", "CreatePalette", "CreatePatternBrush", "CreatePen", "CreatePenIndirect", "CreatePolyPolygonRgn", "CreatePolygonRgn", "CreateRectRgn", "CreateRectRgnIndirect", "CreateRoundRectRgn", "CreateScalableFontResourceA", "CreateScalableFontResourceW", "CreateSolidBrush", "D3DKMTAcquireKeyedMutex", "D3DKMTCheckExclusiveOwnership", "D3DKMTCheckMonitorPowerState", "D3DKMTCheckOcclusion", "D3DKMTCheckSharedResourceAccess", "D3DKMTCheckVidPnExclusiveOwnership", "D3DKMTCloseAdapter", "D3DKMTConfigureSharedResource", "D3DKMTCreateAllocation", "D3DKMTCreateAllocation2", "D3DKMTCreateContext", "D3DKMTCreateDCFromMemory", "D3DKMTCreateDevice", "D3DKMTCreateKeyedMutex", "D3DKMTCreateOverlay", "D3DKMTCreateSynchronizationObject", "D3DKMTCreateSynchronizationObject2", "D3DKMTDestroyAllocation", "D3DKMTDestroyContext", "D3DKMTDestroyDCFromMemory", "D3DKMTDestroyDevice", "D3DKMTDestroyKeyedMutex", "D3DKMTDestroyOverlay", "D3DKMTDestroySynchronizationObject", "D3DKMTEscape", "D3DKMTFlipOverlay", "D3DKMTGetContextSchedulingPriority", "D3DKMTGetDeviceState", "D3DKMTGetDisplayModeList", "D3DKMTGetMultisampleMethodList", "D3DKMTGetOverlayState", "D3DKMTGetPresentHistory", "D3DKMTGetPresentQueueEvent", "D3DKMTGetProcessSchedulingPriorityClass", "D3DKMTGetRuntimeData", "D3DKMTGetScanLine", "D3DKMTGetSharedPrimaryHandle", "D3DKMTInvalidateActiveVidPn", "D3DKMTLock", "D3DKMTOpenAdapterFromDeviceName", "D3DKMTOpenAdapterFromGdiDisplayName", "D3DKMTOpenAdapterFromHdc", "D3DKMTOpenKeyedMutex", "D3DKMTOpenResource", "D3DKMTOpenResource2", "D3DKMTOpenSynchronizationObject", "D3DKMTPollDisplayChildren", "D3DKMTPresent", "D3DKMTQueryAdapterInfo", "D3DKMTQueryAllocationResidency", "D3DKMTQueryResourceInfo", "D3DKMTQueryStatistics", "D3DKMTReleaseKeyedMutex", "D3DKMTReleaseProcessVidPnSourceOwners", "D3DKMTRender", "D3DKMTSetAllocationPriority", "D3DKMTSetContextSchedulingPriority", "D3DKMTSetDisplayMode", "D3DKMTSetDisplayPrivateDriverFormat", "D3DKMTSetGammaRamp", "D3DKMTSetProcessSchedulingPriorityClass", "D3DKMTSetQueuedLimit", "D3DKMTSetVidPnSourceOwner", "D3DKMTSharedPrimaryLockNotification", "D3DKMTSharedPrimaryUnLockNotification", "D3DKMTSignalSynchronizationObject", "D3DKMTSignalSynchronizationObject2", "D3DKMTUnlock", "D3DKMTUpdateOverlay", "D3DKMTWaitForIdle", "D3DKMTWaitForSynchronizationObject", "D3DKMTWaitForSynchronizationObject2", "D3DKMTWaitForVerticalBlankEvent", "DDCCIGetCapabilitiesString", "DDCCIGetCapabilitiesStringLength", "DDCCIGetTimingReport", "DDCCIGetVCPFeature", "DDCCISaveCurrentSettings", "DDCCISetVCPFeature", "DPtoLP", "DdCreateFullscreenSprite", "DdDestroyFullscreenSprite", "DdEntry0", "DdEntry1", "DdEntry10", "DdEntry11", "DdEntry12", "DdEntry13", "DdEntry14", "DdEntry15", "DdEntry16", "DdEntry17", "DdEntry18", "DdEntry19", "DdEntry2", "DdEntry20", "DdEntry21", "DdEntry22", "DdEntry23", "DdEntry24", "DdEntry25", "DdEntry26", "DdEntry27", "DdEntry28", "DdEntry29", "DdEntry3", "DdEntry30", "DdEntry31", "DdEntry32", "DdEntry33", "DdEntry34", "DdEntry35", "DdEntry36", "DdEntry37", "DdEntry38", "DdEntry39", "DdEntry4", "DdEntry40", "DdEntry41", "DdEntry42", "DdEntry43", "DdEntry44", "DdEntry45", "DdEntry46", "DdEntry47", "DdEntry48", "DdEntry49", "DdEntry5", "DdEntry50", "DdEntry51", "DdEntry52", "DdEntry53", "DdEntry54", "DdEntry55", "DdEntry56", "DdEntry6", "DdEntry7", "DdEntry8", "DdEntry9", "DdNotifyFullscreenSpriteUpdate", "DdQueryVisRgnUniqueness", "DeleteColorSpace", "DeleteDC", "DeleteEnhMetaFile", "DeleteMetaFile", "DeleteObject", "DescribePixelFormat", "DestroyOPMProtectedOutput", "DestroyPhysicalMonitorInternal", "DeviceCapabilitiesExA", "DeviceCapabilitiesExW", "DrawEscape", "Ellipse", "EnableEUDC", "EndDoc", "EndFormPage", "EndGdiRendering", "EndPage", "EndPath", "EngAcquireSemaphore", "EngAlphaBlend", "EngAssociateSurface", "EngBitBlt", "EngCheckAbort", "EngComputeGlyphSet", "EngCopyBits", "EngCreateBitmap", "EngCreateClip", "EngCreateDeviceBitmap", "EngCreateDeviceSurface", "EngCreatePalette", "EngCreateSemaphore", "EngDeleteClip", "EngDeletePalette", "EngDeletePath", "EngDeleteSemaphore", "EngDeleteSurface", "EngEraseSurface", "EngFillPath", "EngFindResource", "EngFreeModule", "EngGetCurrentCodePage", "EngGetDriverName", "EngGetPrinterDataFileName", "EngGradientFill", "EngLineTo", "EngLoadModule", "EngLockSurface", "EngMarkBandingSurface", "EngMultiByteToUnicodeN", "EngMultiByteToWideChar", "EngPaint", "EngPlgBlt", "EngQueryEMFInfo", "EngQueryLocalTime", "EngReleaseSemaphore", "EngStretchBlt", "EngStretchBltROP", "EngStrokeAndFillPath", "EngStrokePath", "EngTextOut", "EngTransparentBlt", "EngUnicodeToMultiByteN", "EngUnlockSurface", "EngWideCharToMultiByte", "EnumEnhMetaFile", "EnumFontFamiliesA", "EnumFontFamiliesExA", "EnumFontFamiliesExW", "EnumFontFamiliesW", "EnumFontsA", "EnumFontsW", "EnumICMProfilesA", "EnumICMProfilesW", "EnumMetaFile", "EnumObjects", "EqualRgn", "Escape", "EudcLoadLinkW", "EudcUnloadLinkW", "ExcludeClipRect", "ExtCreatePen", "ExtCreateRegion", "ExtEscape", "ExtFloodFill", "ExtSelectClipRgn", "ExtTextOutA", "ExtTextOutW", "FONTOBJ_cGetAllGlyphHandles", "FONTOBJ_cGetGlyphs", "FONTOBJ_pQueryGlyphAttrs", "FONTOBJ_pfdg", "FONTOBJ_pifi", "FONTOBJ_pvTrueTypeFontFile", "FONTOBJ_pxoGetXform", "FONTOBJ_vGetInfo", "FillPath", "FillRgn", "FixBrushOrgEx", "FlattenPath", "FloodFill", "FontIsLinked", "FrameRgn", "GdiAddFontResourceW", "GdiAddGlsBounds", "GdiAddGlsRecord", "GdiAlphaBlend", "GdiArtificialDecrementDriver", "GdiCleanCacheDC", "GdiComment", "GdiConsoleTextOut", "GdiConvertAndCheckDC", "GdiConvertBitmap", "GdiConvertBitmapV5", "GdiConvertBrush", "GdiConvertDC", "GdiConvertEnhMetaFile", "GdiConvertFont", "GdiConvertMetaFilePict", "GdiConvertPalette", "GdiConvertRegion", "GdiConvertToDevmodeW", "GdiCreateLocalEnhMetaFile", "GdiCreateLocalMetaFilePict", "GdiDeleteLocalDC", "GdiDeleteSpoolFileHandle", "GdiDescribePixelFormat", "GdiDllInitialize", "GdiDrawStream", "GdiEndDocEMF", "GdiEndPageEMF", "GdiEntry1", "GdiEntry10", "GdiEntry11", "GdiEntry12", "GdiEntry13", "GdiEntry14", "GdiEntry15", "GdiEntry16", "GdiEntry2", "GdiEntry3", "GdiEntry4", "GdiEntry5", "GdiEntry6", "GdiEntry7", "GdiEntry8", "GdiEntry9", "GdiFixUpHandle", "GdiFlush", "GdiFullscreenControl", "GdiGetBatchLimit", "GdiGetBitmapBitsSize", "GdiGetCharDimensions", "GdiGetCodePage", "GdiGetDC", "GdiGetDevmodeForPage", "GdiGetLocalBrush", "GdiGetLocalDC", "GdiGetLocalFont", "GdiGetPageCount", "GdiGetPageHandle", "GdiGetSpoolFileHandle", "GdiGetSpoolMessage", "GdiGradientFill", "GdiInitSpool", "GdiInitializeLanguagePack", "GdiIsMetaFileDC", "GdiIsMetaPrintDC", "GdiIsPlayMetafileDC", "GdiIsScreenDC", "GdiLoadType1Fonts", "GdiPlayDCScript", "GdiPlayEMF", "GdiPlayJournal", "GdiPlayPageEMF", "GdiPlayPrivatePageEMF", "GdiPlayScript", "GdiPrinterThunk", "GdiProcessSetup", "GdiQueryFonts", "GdiQueryTable", "GdiRealizationInfo", "GdiReleaseDC", "GdiReleaseLocalDC", "GdiResetDCEMF", "GdiSetAttrs", "GdiSetBatchLimit", "GdiSetLastError", "GdiSetPixelFormat", "GdiSetServerAttr", "GdiStartDocEMF", "GdiStartPageEMF", "GdiSwapBuffers", "GdiTransparentBlt", "GdiValidateHandle", "GetArcDirection", "GetAspectRatioFilterEx", "GetBitmapAttributes", "GetBitmapBits", "GetBitmapDimensionEx", "GetBkColor", "GetBkMode", "GetBoundsRect", "GetBrushAttributes", "GetBrushOrgEx", "GetCOPPCompatibleOPMInformation", "GetCertificate", "GetCertificateSize", "GetCharABCWidthsA", "GetCharABCWidthsFloatA", "GetCharABCWidthsFloatW", "GetCharABCWidthsI", "GetCharABCWidthsW", "GetCharWidth32A", "GetCharWidth32W", "GetCharWidthA", "GetCharWidthFloatA", "GetCharWidthFloatW", "GetCharWidthI", "GetCharWidthInfo", "GetCharWidthW", "GetCharacterPlacementA", "GetCharacterPlacementW", "GetClipBox", "GetClipRgn", "GetColorAdjustment", "GetColorSpace", "GetCurrentObject", "GetCurrentPositionEx", "GetDCBrushColor", "GetDCOrgEx", "GetDCPenColor", "GetDIBColorTable", "GetDIBits", "GetDeviceCaps", "GetDeviceGammaRamp", "GetETM", "GetEUDCTimeStamp", "GetEUDCTimeStampExW", "GetEnhMetaFileA", "GetEnhMetaFileBits", "GetEnhMetaFileDescriptionA", "GetEnhMetaFileDescriptionW", "GetEnhMetaFileHeader", "GetEnhMetaFilePaletteEntries", "GetEnhMetaFilePixelFormat", "GetEnhMetaFileW", "GetFontAssocStatus", "GetFontData", "GetFontFileData", "GetFontFileInfo", "GetFontLanguageInfo", "GetFontRealizationInfo", "GetFontResourceInfoW", "GetFontUnicodeRanges", "GetGlyphIndicesA", "GetGlyphIndicesW", "GetGlyphOutline", "GetGlyphOutlineA", "GetGlyphOutlineW", "GetGlyphOutlineWow", "GetGraphicsMode", "GetHFONT", "GetICMProfileA", "GetICMProfileW", "GetKerningPairs", "GetKerningPairsA", "GetKerningPairsW", "GetLayout", "GetLogColorSpaceA", "GetLogColorSpaceW", "GetMapMode", "GetMetaFileA", "GetMetaFileBitsEx", "GetMetaFileW", "GetMetaRgn", "GetMiterLimit", "GetNearestColor", "GetNearestPaletteIndex", "GetNumberOfPhysicalMonitors", "GetOPMInformation", "GetOPMRandomNumber", "GetObjectA", "GetObjectType", "GetObjectW", "GetOutlineTextMetricsA", "GetOutlineTextMetricsW", "GetPaletteEntries", "GetPath", "GetPhysicalMonitorDescription", "GetPhysicalMonitors", "GetPixel", "GetPixelFormat", "GetPolyFillMode", "GetROP2", "GetRandomRgn", "GetRasterizerCaps", "GetRegionData", "GetRelAbs", "GetRgnBox", "GetStockObject", "GetStretchBltMode", "GetStringBitmapA", "GetStringBitmapW", "GetSuggestedOPMProtectedOutputArraySize", "GetSystemPaletteEntries", "GetSystemPaletteUse", "GetTextAlign", "GetTextCharacterExtra", "GetTextCharset", "GetTextCharsetInfo", "GetTextColor", "GetTextExtentExPointA", "GetTextExtentExPointI", "GetTextExtentExPointW", "GetTextExtentExPointWPri", "GetTextExtentPoint32A", "GetTextExtentPoint32W", "GetTextExtentPointA", "GetTextExtentPointI", "GetTextExtentPointW", "GetTextFaceA", "GetTextFaceAliasW", "GetTextFaceW", "GetTextMetricsA", "GetTextMetricsW", "GetTransform", "GetViewportExtEx", "GetViewportOrgEx", "GetWinMetaFileBits", "GetWindowExtEx", "GetWindowOrgEx", "GetWorldTransform", "HT_Get8BPPFormatPalette", "HT_Get8BPPMaskPalette", "IntersectClipRect", "InvertRgn", "IsValidEnhMetaRecord", "IsValidEnhMetaRecordOffExt", "LPtoDP", "LineDDA", "LineTo", "MaskBlt", "MirrorRgn", "ModifyWorldTransform", "MoveToEx", "NamedEscape", "OffsetClipRgn", "OffsetRgn", "OffsetViewportOrgEx", "OffsetWindowOrgEx", "PATHOBJ_bEnum", "PATHOBJ_bEnumClipLines", "PATHOBJ_vEnumStart", "PATHOBJ_vEnumStartClipLines", "PATHOBJ_vGetBounds", "PaintRgn", "PatBlt", "PathToRegion", "Pie", "PlayEnhMetaFile", "PlayEnhMetaFileRecord", "PlayMetaFile", "PlayMetaFileRecord", "PlgBlt", "PolyBezier", "PolyBezierTo", "PolyDraw", "PolyPatBlt", "PolyPolygon", "PolyPolyline", "PolyTextOutA", "PolyTextOutW", "Polygon", "Polyline", "PolylineTo", "PtInRegion", "PtVisible", "QueryFontAssocStatus", "RealizePalette", "RectInRegion", "RectVisible", "Rectangle", "RemoveFontMemResourceEx", "RemoveFontResourceA", "RemoveFontResourceExA", "RemoveFontResourceExW", "RemoveFontResourceTracking", "RemoveFontResourceW", "ResetDCA", "ResetDCW", "ResizePalette", "RestoreDC", "RoundRect", "STROBJ_bEnum", "STROBJ_bEnumPositionsOnly", "STROBJ_bGetAdvanceWidths", "STROBJ_dwGetCodePage", "STROBJ_vEnumStart", "SaveDC", "ScaleViewportExtEx", "ScaleWindowExtEx", "SelectBrushLocal", "SelectClipPath", "SelectClipRgn", "SelectFontLocal", "SelectObject", "SelectPalette", "SetAbortProc", "SetArcDirection", "SetBitmapAttributes", "SetBitmapBits", "SetBitmapDimensionEx", "SetBkColor", "SetBkMode", "SetBoundsRect", "SetBrushAttributes", "SetBrushOrgEx", "SetColorAdjustment", "SetColorSpace", "SetDCBrushColor", "SetDCPenColor", "SetDIBColorTable", "SetDIBits", "SetDIBitsToDevice", "SetDeviceGammaRamp", "SetEnhMetaFileBits", "SetFontEnumeration", "SetGraphicsMode", "SetICMMode", "SetICMProfileA", "SetICMProfileW", "SetLayout", "SetLayoutWidth", "SetMagicColors", "SetMapMode", "SetMapperFlags", "SetMetaFileBitsEx", "SetMetaRgn", "SetMiterLimit", "SetOPMSigningKeyAndSequenceNumbers", "SetPaletteEntries", "SetPixel", "SetPixelFormat", "SetPixelV", "SetPolyFillMode", "SetROP2", "SetRectRgn", "SetRelAbs", "SetStretchBltMode", "SetSystemPaletteUse", "SetTextAlign", "SetTextCharacterExtra", "SetTextColor", "SetTextJustification", "SetViewportExtEx", "SetViewportOrgEx", "SetVirtualResolution", "SetWinMetaFileBits", "SetWindowExtEx", "SetWindowOrgEx", "SetWorldTransform", "StartDocA", "StartDocW", "StartFormPage", "StartPage", "StretchBlt", "StretchDIBits", "StrokeAndFillPath", "StrokePath", "SwapBuffers", "TextOutA", "TextOutW", "TranslateCharsetInfo", "UnloadNetworkFonts", "UnrealizeObject", "UpdateColors", "UpdateICMRegKeyA", "UpdateICMRegKeyW", "WidenPath", "XFORMOBJ_bApplyXform", "XFORMOBJ_iGetXform", "XLATEOBJ_cGetPalette", "XLATEOBJ_hGetColorTransform", "XLATEOBJ_iXlate", "XLATEOBJ_piVector", "bInitSystemAndFontsDirectoriesW", "bMakePathNameW", "cGetTTFFromFOT", "gdiPlaySpoolStream", (LPCSTR)1000, (LPCSTR)1001, (LPCSTR)1002, (LPCSTR)1003, (LPCSTR)1004, (LPCSTR)1005, (LPCSTR)1006, (LPCSTR)1007, (LPCSTR)1008, (LPCSTR)1009, (LPCSTR)1010, (LPCSTR)1011};

BOOL WINAPI DllMain( HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved ) {
	mHinst = hinstDLL;
	if ( fdwReason == DLL_PROCESS_ATTACH ) {
		mHinstDLL = LoadLibrary( "C:\\Windows\\SysWOW64\\gdi32.dll" );
		if ( !mHinstDLL )
			return ( FALSE );
		for (int i = 0; i < 727; i++)
		{
			mProcs[i] = (UINT_PTR)GetProcAddress(mHinstDLL, mImportNames[i]);
		}
	} else if ( fdwReason == DLL_PROCESS_DETACH ) {
		FreeLibrary( mHinstDLL );
	}
	return ( TRUE );
}

extern "C" __declspec(naked) void __stdcall AbortDoc_wrapper(){__asm{jmp mProcs[0*4]}}
extern "C" __declspec(naked) void __stdcall AbortPath_wrapper(){__asm{jmp mProcs[1*4]}}
extern "C" __declspec(naked) void __stdcall AddFontMemResourceEx_wrapper(){__asm{jmp mProcs[2*4]}}
extern "C" __declspec(naked) void __stdcall AddFontResourceA_wrapper(){__asm{jmp mProcs[3*4]}}
extern "C" __declspec(naked) void __stdcall AddFontResourceExA_wrapper(){__asm{jmp mProcs[4*4]}}
extern "C" __declspec(naked) void __stdcall AddFontResourceExW_wrapper(){__asm{jmp mProcs[5*4]}}
extern "C" __declspec(naked) void __stdcall AddFontResourceTracking_wrapper(){__asm{jmp mProcs[6*4]}}
extern "C" __declspec(naked) void __stdcall AddFontResourceW_wrapper(){__asm{jmp mProcs[7*4]}}
extern "C" __declspec(naked) void __stdcall AngleArc_wrapper(){__asm{jmp mProcs[8*4]}}
extern "C" __declspec(naked) void __stdcall AnimatePalette_wrapper(){__asm{jmp mProcs[9*4]}}
extern "C" __declspec(naked) void __stdcall AnyLinkedFonts_wrapper(){__asm{jmp mProcs[10*4]}}
extern "C" __declspec(naked) void __stdcall Arc_wrapper(){__asm{jmp mProcs[11*4]}}
extern "C" __declspec(naked) void __stdcall ArcTo_wrapper(){__asm{jmp mProcs[12*4]}}
extern "C" __declspec(naked) void __stdcall BRUSHOBJ_hGetColorTransform_wrapper(){__asm{jmp mProcs[13*4]}}
extern "C" __declspec(naked) void __stdcall BRUSHOBJ_pvAllocRbrush_wrapper(){__asm{jmp mProcs[14*4]}}
extern "C" __declspec(naked) void __stdcall BRUSHOBJ_pvGetRbrush_wrapper(){__asm{jmp mProcs[15*4]}}
extern "C" __declspec(naked) void __stdcall BRUSHOBJ_ulGetBrushColor_wrapper(){__asm{jmp mProcs[16*4]}}
extern "C" __declspec(naked) void __stdcall BeginGdiRendering_wrapper(){__asm{jmp mProcs[17*4]}}
extern "C" __declspec(naked) void __stdcall BeginPath_wrapper(){__asm{jmp mProcs[18*4]}}
extern "C" __declspec(naked) void __stdcall BitBlt_wrapper(){__asm{jmp mProcs[19*4]}}
extern "C" __declspec(naked) void __stdcall CLIPOBJ_bEnum_wrapper(){__asm{jmp mProcs[20*4]}}
extern "C" __declspec(naked) void __stdcall CLIPOBJ_cEnumStart_wrapper(){__asm{jmp mProcs[21*4]}}
extern "C" __declspec(naked) void __stdcall CLIPOBJ_ppoGetPath_wrapper(){__asm{jmp mProcs[22*4]}}
extern "C" __declspec(naked) void __stdcall CancelDC_wrapper(){__asm{jmp mProcs[23*4]}}
extern "C" __declspec(naked) void __stdcall CheckColorsInGamut_wrapper(){__asm{jmp mProcs[24*4]}}
extern "C" __declspec(naked) void __stdcall ChoosePixelFormat_wrapper(){__asm{jmp mProcs[25*4]}}
extern "C" __declspec(naked) void __stdcall Chord_wrapper(){__asm{jmp mProcs[26*4]}}
extern "C" __declspec(naked) void __stdcall ClearBitmapAttributes_wrapper(){__asm{jmp mProcs[27*4]}}
extern "C" __declspec(naked) void __stdcall ClearBrushAttributes_wrapper(){__asm{jmp mProcs[28*4]}}
extern "C" __declspec(naked) void __stdcall CloseEnhMetaFile_wrapper(){__asm{jmp mProcs[29*4]}}
extern "C" __declspec(naked) void __stdcall CloseFigure_wrapper(){__asm{jmp mProcs[30*4]}}
extern "C" __declspec(naked) void __stdcall CloseMetaFile_wrapper(){__asm{jmp mProcs[31*4]}}
extern "C" __declspec(naked) void __stdcall ColorCorrectPalette_wrapper(){__asm{jmp mProcs[32*4]}}
extern "C" __declspec(naked) void __stdcall ColorMatchToTarget_wrapper(){__asm{jmp mProcs[33*4]}}
extern "C" __declspec(naked) void __stdcall CombineRgn_wrapper(){__asm{jmp mProcs[34*4]}}
extern "C" __declspec(naked) void __stdcall CombineTransform_wrapper(){__asm{jmp mProcs[35*4]}}
extern "C" __declspec(naked) void __stdcall ConfigureOPMProtectedOutput_wrapper(){__asm{jmp mProcs[36*4]}}
extern "C" __declspec(naked) void __stdcall CopyEnhMetaFileA_wrapper(){__asm{jmp mProcs[37*4]}}
extern "C" __declspec(naked) void __stdcall CopyEnhMetaFileW_wrapper(){__asm{jmp mProcs[38*4]}}
extern "C" __declspec(naked) void __stdcall CopyMetaFileA_wrapper(){__asm{jmp mProcs[39*4]}}
extern "C" __declspec(naked) void __stdcall CopyMetaFileW_wrapper(){__asm{jmp mProcs[40*4]}}
extern "C" __declspec(naked) void __stdcall CreateBitmap_wrapper(){__asm{jmp mProcs[41*4]}}
extern "C" __declspec(naked) void __stdcall CreateBitmapFromDxSurface_wrapper(){__asm{jmp mProcs[42*4]}}
extern "C" __declspec(naked) void __stdcall CreateBitmapIndirect_wrapper(){__asm{jmp mProcs[43*4]}}
extern "C" __declspec(naked) void __stdcall CreateBrushIndirect_wrapper(){__asm{jmp mProcs[44*4]}}
extern "C" __declspec(naked) void __stdcall CreateColorSpaceA_wrapper(){__asm{jmp mProcs[45*4]}}
extern "C" __declspec(naked) void __stdcall CreateColorSpaceW_wrapper(){__asm{jmp mProcs[46*4]}}
extern "C" __declspec(naked) void __stdcall CreateCompatibleBitmap_wrapper(){__asm{jmp mProcs[47*4]}}
extern "C" __declspec(naked) void __stdcall CreateCompatibleDC_wrapper(){__asm{jmp mProcs[48*4]}}
extern "C" __declspec(naked) void __stdcall CreateDCA_wrapper(){__asm{jmp mProcs[49*4]}}
extern "C" __declspec(naked) void __stdcall CreateDCW_wrapper(){__asm{jmp mProcs[50*4]}}
extern "C" __declspec(naked) void __stdcall CreateDIBPatternBrush_wrapper(){__asm{jmp mProcs[51*4]}}
extern "C" __declspec(naked) void __stdcall CreateDIBPatternBrushPt_wrapper(){__asm{jmp mProcs[52*4]}}
extern "C" __declspec(naked) void __stdcall CreateDIBSection_wrapper(){__asm{jmp mProcs[53*4]}}
extern "C" __declspec(naked) void __stdcall CreateDIBitmap_wrapper(){__asm{jmp mProcs[54*4]}}
extern "C" __declspec(naked) void __stdcall CreateDiscardableBitmap_wrapper(){__asm{jmp mProcs[55*4]}}
extern "C" __declspec(naked) void __stdcall CreateEllipticRgn_wrapper(){__asm{jmp mProcs[56*4]}}
extern "C" __declspec(naked) void __stdcall CreateEllipticRgnIndirect_wrapper(){__asm{jmp mProcs[57*4]}}
extern "C" __declspec(naked) void __stdcall CreateEnhMetaFileA_wrapper(){__asm{jmp mProcs[58*4]}}
extern "C" __declspec(naked) void __stdcall CreateEnhMetaFileW_wrapper(){__asm{jmp mProcs[59*4]}}
extern "C" __declspec(naked) void __stdcall CreateFontA_wrapper(){__asm{jmp mProcs[60*4]}}
extern "C" __declspec(naked) void __stdcall CreateFontIndirectA_wrapper(){__asm{jmp mProcs[61*4]}}
extern "C" __declspec(naked) void __stdcall CreateFontIndirectExA_wrapper(){__asm{jmp mProcs[62*4]}}
extern "C" __declspec(naked) void __stdcall CreateFontIndirectExW_wrapper(){__asm{jmp mProcs[63*4]}}
extern "C" __declspec(naked) void __stdcall CreateFontIndirectW_wrapper(){__asm{jmp mProcs[64*4]}}
extern "C" __declspec(naked) void __stdcall CreateFontW_wrapper(){__asm{jmp mProcs[65*4]}}
extern "C" __declspec(naked) void __stdcall CreateHalftonePalette_wrapper(){__asm{jmp mProcs[66*4]}}
extern "C" __declspec(naked) void __stdcall CreateHatchBrush_wrapper(){__asm{jmp mProcs[67*4]}}
extern "C" __declspec(naked) void __stdcall CreateICA_wrapper(){__asm{jmp mProcs[68*4]}}
extern "C" __declspec(naked) void __stdcall CreateICW_wrapper(){__asm{jmp mProcs[69*4]}}
extern "C" __declspec(naked) void __stdcall CreateMetaFileA_wrapper(){__asm{jmp mProcs[70*4]}}
extern "C" __declspec(naked) void __stdcall CreateMetaFileW_wrapper(){__asm{jmp mProcs[71*4]}}
extern "C" __declspec(naked) void __stdcall CreateOPMProtectedOutputs_wrapper(){__asm{jmp mProcs[72*4]}}
extern "C" __declspec(naked) void __stdcall CreatePalette_wrapper(){__asm{jmp mProcs[73*4]}}
extern "C" __declspec(naked) void __stdcall CreatePatternBrush_wrapper(){__asm{jmp mProcs[74*4]}}
extern "C" __declspec(naked) void __stdcall CreatePen_wrapper(){__asm{jmp mProcs[75*4]}}
extern "C" __declspec(naked) void __stdcall CreatePenIndirect_wrapper(){__asm{jmp mProcs[76*4]}}
extern "C" __declspec(naked) void __stdcall CreatePolyPolygonRgn_wrapper(){__asm{jmp mProcs[77*4]}}
extern "C" __declspec(naked) void __stdcall CreatePolygonRgn_wrapper(){__asm{jmp mProcs[78*4]}}
extern "C" __declspec(naked) void __stdcall CreateRectRgn_wrapper(){__asm{jmp mProcs[79*4]}}
extern "C" __declspec(naked) void __stdcall CreateRectRgnIndirect_wrapper(){__asm{jmp mProcs[80*4]}}
extern "C" __declspec(naked) void __stdcall CreateRoundRectRgn_wrapper(){__asm{jmp mProcs[81*4]}}
extern "C" __declspec(naked) void __stdcall CreateScalableFontResourceA_wrapper(){__asm{jmp mProcs[82*4]}}
extern "C" __declspec(naked) void __stdcall CreateScalableFontResourceW_wrapper(){__asm{jmp mProcs[83*4]}}
extern "C" __declspec(naked) void __stdcall CreateSolidBrush_wrapper(){__asm{jmp mProcs[84*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTAcquireKeyedMutex_wrapper(){__asm{jmp mProcs[85*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCheckExclusiveOwnership_wrapper(){__asm{jmp mProcs[86*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCheckMonitorPowerState_wrapper(){__asm{jmp mProcs[87*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCheckOcclusion_wrapper(){__asm{jmp mProcs[88*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCheckSharedResourceAccess_wrapper(){__asm{jmp mProcs[89*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCheckVidPnExclusiveOwnership_wrapper(){__asm{jmp mProcs[90*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCloseAdapter_wrapper(){__asm{jmp mProcs[91*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTConfigureSharedResource_wrapper(){__asm{jmp mProcs[92*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCreateAllocation_wrapper(){__asm{jmp mProcs[93*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCreateAllocation2_wrapper(){__asm{jmp mProcs[94*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCreateContext_wrapper(){__asm{jmp mProcs[95*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCreateDCFromMemory_wrapper(){__asm{jmp mProcs[96*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCreateDevice_wrapper(){__asm{jmp mProcs[97*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCreateKeyedMutex_wrapper(){__asm{jmp mProcs[98*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCreateOverlay_wrapper(){__asm{jmp mProcs[99*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCreateSynchronizationObject_wrapper(){__asm{jmp mProcs[100*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTCreateSynchronizationObject2_wrapper(){__asm{jmp mProcs[101*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTDestroyAllocation_wrapper(){__asm{jmp mProcs[102*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTDestroyContext_wrapper(){__asm{jmp mProcs[103*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTDestroyDCFromMemory_wrapper(){__asm{jmp mProcs[104*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTDestroyDevice_wrapper(){__asm{jmp mProcs[105*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTDestroyKeyedMutex_wrapper(){__asm{jmp mProcs[106*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTDestroyOverlay_wrapper(){__asm{jmp mProcs[107*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTDestroySynchronizationObject_wrapper(){__asm{jmp mProcs[108*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTEscape_wrapper(){__asm{jmp mProcs[109*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTFlipOverlay_wrapper(){__asm{jmp mProcs[110*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTGetContextSchedulingPriority_wrapper(){__asm{jmp mProcs[111*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTGetDeviceState_wrapper(){__asm{jmp mProcs[112*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTGetDisplayModeList_wrapper(){__asm{jmp mProcs[113*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTGetMultisampleMethodList_wrapper(){__asm{jmp mProcs[114*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTGetOverlayState_wrapper(){__asm{jmp mProcs[115*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTGetPresentHistory_wrapper(){__asm{jmp mProcs[116*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTGetPresentQueueEvent_wrapper(){__asm{jmp mProcs[117*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTGetProcessSchedulingPriorityClass_wrapper(){__asm{jmp mProcs[118*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTGetRuntimeData_wrapper(){__asm{jmp mProcs[119*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTGetScanLine_wrapper(){__asm{jmp mProcs[120*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTGetSharedPrimaryHandle_wrapper(){__asm{jmp mProcs[121*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTInvalidateActiveVidPn_wrapper(){__asm{jmp mProcs[122*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTLock_wrapper(){__asm{jmp mProcs[123*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTOpenAdapterFromDeviceName_wrapper(){__asm{jmp mProcs[124*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTOpenAdapterFromGdiDisplayName_wrapper(){__asm{jmp mProcs[125*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTOpenAdapterFromHdc_wrapper(){__asm{jmp mProcs[126*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTOpenKeyedMutex_wrapper(){__asm{jmp mProcs[127*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTOpenResource_wrapper(){__asm{jmp mProcs[128*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTOpenResource2_wrapper(){__asm{jmp mProcs[129*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTOpenSynchronizationObject_wrapper(){__asm{jmp mProcs[130*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTPollDisplayChildren_wrapper(){__asm{jmp mProcs[131*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTPresent_wrapper(){__asm{jmp mProcs[132*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTQueryAdapterInfo_wrapper(){__asm{jmp mProcs[133*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTQueryAllocationResidency_wrapper(){__asm{jmp mProcs[134*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTQueryResourceInfo_wrapper(){__asm{jmp mProcs[135*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTQueryStatistics_wrapper(){__asm{jmp mProcs[136*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTReleaseKeyedMutex_wrapper(){__asm{jmp mProcs[137*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTReleaseProcessVidPnSourceOwners_wrapper(){__asm{jmp mProcs[138*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTRender_wrapper(){__asm{jmp mProcs[139*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTSetAllocationPriority_wrapper(){__asm{jmp mProcs[140*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTSetContextSchedulingPriority_wrapper(){__asm{jmp mProcs[141*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTSetDisplayMode_wrapper(){__asm{jmp mProcs[142*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTSetDisplayPrivateDriverFormat_wrapper(){__asm{jmp mProcs[143*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTSetGammaRamp_wrapper(){__asm{jmp mProcs[144*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTSetProcessSchedulingPriorityClass_wrapper(){__asm{jmp mProcs[145*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTSetQueuedLimit_wrapper(){__asm{jmp mProcs[146*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTSetVidPnSourceOwner_wrapper(){__asm{jmp mProcs[147*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTSharedPrimaryLockNotification_wrapper(){__asm{jmp mProcs[148*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTSharedPrimaryUnLockNotification_wrapper(){__asm{jmp mProcs[149*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTSignalSynchronizationObject_wrapper(){__asm{jmp mProcs[150*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTSignalSynchronizationObject2_wrapper(){__asm{jmp mProcs[151*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTUnlock_wrapper(){__asm{jmp mProcs[152*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTUpdateOverlay_wrapper(){__asm{jmp mProcs[153*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTWaitForIdle_wrapper(){__asm{jmp mProcs[154*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTWaitForSynchronizationObject_wrapper(){__asm{jmp mProcs[155*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTWaitForSynchronizationObject2_wrapper(){__asm{jmp mProcs[156*4]}}
extern "C" __declspec(naked) void __stdcall D3DKMTWaitForVerticalBlankEvent_wrapper(){__asm{jmp mProcs[157*4]}}
extern "C" __declspec(naked) void __stdcall DDCCIGetCapabilitiesString_wrapper(){__asm{jmp mProcs[158*4]}}
extern "C" __declspec(naked) void __stdcall DDCCIGetCapabilitiesStringLength_wrapper(){__asm{jmp mProcs[159*4]}}
extern "C" __declspec(naked) void __stdcall DDCCIGetTimingReport_wrapper(){__asm{jmp mProcs[160*4]}}
extern "C" __declspec(naked) void __stdcall DDCCIGetVCPFeature_wrapper(){__asm{jmp mProcs[161*4]}}
extern "C" __declspec(naked) void __stdcall DDCCISaveCurrentSettings_wrapper(){__asm{jmp mProcs[162*4]}}
extern "C" __declspec(naked) void __stdcall DDCCISetVCPFeature_wrapper(){__asm{jmp mProcs[163*4]}}
extern "C" __declspec(naked) void __stdcall DPtoLP_wrapper(){__asm{jmp mProcs[164*4]}}
extern "C" __declspec(naked) void __stdcall DdCreateFullscreenSprite_wrapper(){__asm{jmp mProcs[165*4]}}
extern "C" __declspec(naked) void __stdcall DdDestroyFullscreenSprite_wrapper(){__asm{jmp mProcs[166*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry0_wrapper(){__asm{jmp mProcs[167*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry1_wrapper(){__asm{jmp mProcs[168*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry10_wrapper(){__asm{jmp mProcs[169*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry11_wrapper(){__asm{jmp mProcs[170*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry12_wrapper(){__asm{jmp mProcs[171*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry13_wrapper(){__asm{jmp mProcs[172*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry14_wrapper(){__asm{jmp mProcs[173*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry15_wrapper(){__asm{jmp mProcs[174*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry16_wrapper(){__asm{jmp mProcs[175*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry17_wrapper(){__asm{jmp mProcs[176*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry18_wrapper(){__asm{jmp mProcs[177*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry19_wrapper(){__asm{jmp mProcs[178*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry2_wrapper(){__asm{jmp mProcs[179*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry20_wrapper(){__asm{jmp mProcs[180*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry21_wrapper(){__asm{jmp mProcs[181*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry22_wrapper(){__asm{jmp mProcs[182*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry23_wrapper(){__asm{jmp mProcs[183*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry24_wrapper(){__asm{jmp mProcs[184*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry25_wrapper(){__asm{jmp mProcs[185*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry26_wrapper(){__asm{jmp mProcs[186*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry27_wrapper(){__asm{jmp mProcs[187*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry28_wrapper(){__asm{jmp mProcs[188*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry29_wrapper(){__asm{jmp mProcs[189*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry3_wrapper(){__asm{jmp mProcs[190*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry30_wrapper(){__asm{jmp mProcs[191*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry31_wrapper(){__asm{jmp mProcs[192*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry32_wrapper(){__asm{jmp mProcs[193*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry33_wrapper(){__asm{jmp mProcs[194*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry34_wrapper(){__asm{jmp mProcs[195*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry35_wrapper(){__asm{jmp mProcs[196*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry36_wrapper(){__asm{jmp mProcs[197*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry37_wrapper(){__asm{jmp mProcs[198*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry38_wrapper(){__asm{jmp mProcs[199*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry39_wrapper(){__asm{jmp mProcs[200*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry4_wrapper(){__asm{jmp mProcs[201*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry40_wrapper(){__asm{jmp mProcs[202*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry41_wrapper(){__asm{jmp mProcs[203*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry42_wrapper(){__asm{jmp mProcs[204*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry43_wrapper(){__asm{jmp mProcs[205*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry44_wrapper(){__asm{jmp mProcs[206*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry45_wrapper(){__asm{jmp mProcs[207*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry46_wrapper(){__asm{jmp mProcs[208*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry47_wrapper(){__asm{jmp mProcs[209*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry48_wrapper(){__asm{jmp mProcs[210*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry49_wrapper(){__asm{jmp mProcs[211*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry5_wrapper(){__asm{jmp mProcs[212*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry50_wrapper(){__asm{jmp mProcs[213*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry51_wrapper(){__asm{jmp mProcs[214*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry52_wrapper(){__asm{jmp mProcs[215*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry53_wrapper(){__asm{jmp mProcs[216*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry54_wrapper(){__asm{jmp mProcs[217*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry55_wrapper(){__asm{jmp mProcs[218*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry56_wrapper(){__asm{jmp mProcs[219*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry6_wrapper(){__asm{jmp mProcs[220*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry7_wrapper(){__asm{jmp mProcs[221*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry8_wrapper(){__asm{jmp mProcs[222*4]}}
extern "C" __declspec(naked) void __stdcall DdEntry9_wrapper(){__asm{jmp mProcs[223*4]}}
extern "C" __declspec(naked) void __stdcall DdNotifyFullscreenSpriteUpdate_wrapper(){__asm{jmp mProcs[224*4]}}
extern "C" __declspec(naked) void __stdcall DdQueryVisRgnUniqueness_wrapper(){__asm{jmp mProcs[225*4]}}
extern "C" __declspec(naked) void __stdcall DeleteColorSpace_wrapper(){__asm{jmp mProcs[226*4]}}
extern "C" __declspec(naked) void __stdcall DeleteDC_wrapper(){__asm{jmp mProcs[227*4]}}
extern "C" __declspec(naked) void __stdcall DeleteEnhMetaFile_wrapper(){__asm{jmp mProcs[228*4]}}
extern "C" __declspec(naked) void __stdcall DeleteMetaFile_wrapper(){__asm{jmp mProcs[229*4]}}
extern "C" __declspec(naked) void __stdcall DeleteObject_wrapper(){__asm{jmp mProcs[230*4]}}
extern "C" __declspec(naked) void __stdcall DescribePixelFormat_wrapper(){__asm{jmp mProcs[231*4]}}
extern "C" __declspec(naked) void __stdcall DestroyOPMProtectedOutput_wrapper(){__asm{jmp mProcs[232*4]}}
extern "C" __declspec(naked) void __stdcall DestroyPhysicalMonitorInternal_wrapper(){__asm{jmp mProcs[233*4]}}
extern "C" __declspec(naked) void __stdcall DeviceCapabilitiesExA_wrapper(){__asm{jmp mProcs[234*4]}}
extern "C" __declspec(naked) void __stdcall DeviceCapabilitiesExW_wrapper(){__asm{jmp mProcs[235*4]}}
extern "C" __declspec(naked) void __stdcall DrawEscape_wrapper(){__asm{jmp mProcs[236*4]}}
extern "C" __declspec(naked) void __stdcall Ellipse_wrapper(){__asm{jmp mProcs[237*4]}}
extern "C" __declspec(naked) void __stdcall EnableEUDC_wrapper(){__asm{jmp mProcs[238*4]}}
extern "C" __declspec(naked) void __stdcall EndDoc_wrapper(){__asm{jmp mProcs[239*4]}}
extern "C" __declspec(naked) void __stdcall EndFormPage_wrapper(){__asm{jmp mProcs[240*4]}}
extern "C" __declspec(naked) void __stdcall EndGdiRendering_wrapper(){__asm{jmp mProcs[241*4]}}
extern "C" __declspec(naked) void __stdcall EndPage_wrapper(){__asm{jmp mProcs[242*4]}}
extern "C" __declspec(naked) void __stdcall EndPath_wrapper(){__asm{jmp mProcs[243*4]}}
extern "C" __declspec(naked) void __stdcall EngAcquireSemaphore_wrapper(){__asm{jmp mProcs[244*4]}}
extern "C" __declspec(naked) void __stdcall EngAlphaBlend_wrapper(){__asm{jmp mProcs[245*4]}}
extern "C" __declspec(naked) void __stdcall EngAssociateSurface_wrapper(){__asm{jmp mProcs[246*4]}}
extern "C" __declspec(naked) void __stdcall EngBitBlt_wrapper(){__asm{jmp mProcs[247*4]}}
extern "C" __declspec(naked) void __stdcall EngCheckAbort_wrapper(){__asm{jmp mProcs[248*4]}}
extern "C" __declspec(naked) void __stdcall EngComputeGlyphSet_wrapper(){__asm{jmp mProcs[249*4]}}
extern "C" __declspec(naked) void __stdcall EngCopyBits_wrapper(){__asm{jmp mProcs[250*4]}}
extern "C" __declspec(naked) void __stdcall EngCreateBitmap_wrapper(){__asm{jmp mProcs[251*4]}}
extern "C" __declspec(naked) void __stdcall EngCreateClip_wrapper(){__asm{jmp mProcs[252*4]}}
extern "C" __declspec(naked) void __stdcall EngCreateDeviceBitmap_wrapper(){__asm{jmp mProcs[253*4]}}
extern "C" __declspec(naked) void __stdcall EngCreateDeviceSurface_wrapper(){__asm{jmp mProcs[254*4]}}
extern "C" __declspec(naked) void __stdcall EngCreatePalette_wrapper(){__asm{jmp mProcs[255*4]}}
extern "C" __declspec(naked) void __stdcall EngCreateSemaphore_wrapper(){__asm{jmp mProcs[256*4]}}
extern "C" __declspec(naked) void __stdcall EngDeleteClip_wrapper(){__asm{jmp mProcs[257*4]}}
extern "C" __declspec(naked) void __stdcall EngDeletePalette_wrapper(){__asm{jmp mProcs[258*4]}}
extern "C" __declspec(naked) void __stdcall EngDeletePath_wrapper(){__asm{jmp mProcs[259*4]}}
extern "C" __declspec(naked) void __stdcall EngDeleteSemaphore_wrapper(){__asm{jmp mProcs[260*4]}}
extern "C" __declspec(naked) void __stdcall EngDeleteSurface_wrapper(){__asm{jmp mProcs[261*4]}}
extern "C" __declspec(naked) void __stdcall EngEraseSurface_wrapper(){__asm{jmp mProcs[262*4]}}
extern "C" __declspec(naked) void __stdcall EngFillPath_wrapper(){__asm{jmp mProcs[263*4]}}
extern "C" __declspec(naked) void __stdcall EngFindResource_wrapper(){__asm{jmp mProcs[264*4]}}
extern "C" __declspec(naked) void __stdcall EngFreeModule_wrapper(){__asm{jmp mProcs[265*4]}}
extern "C" __declspec(naked) void __stdcall EngGetCurrentCodePage_wrapper(){__asm{jmp mProcs[266*4]}}
extern "C" __declspec(naked) void __stdcall EngGetDriverName_wrapper(){__asm{jmp mProcs[267*4]}}
extern "C" __declspec(naked) void __stdcall EngGetPrinterDataFileName_wrapper(){__asm{jmp mProcs[268*4]}}
extern "C" __declspec(naked) void __stdcall EngGradientFill_wrapper(){__asm{jmp mProcs[269*4]}}
extern "C" __declspec(naked) void __stdcall EngLineTo_wrapper(){__asm{jmp mProcs[270*4]}}
extern "C" __declspec(naked) void __stdcall EngLoadModule_wrapper(){__asm{jmp mProcs[271*4]}}
extern "C" __declspec(naked) void __stdcall EngLockSurface_wrapper(){__asm{jmp mProcs[272*4]}}
extern "C" __declspec(naked) void __stdcall EngMarkBandingSurface_wrapper(){__asm{jmp mProcs[273*4]}}
extern "C" __declspec(naked) void __stdcall EngMultiByteToUnicodeN_wrapper(){__asm{jmp mProcs[274*4]}}
extern "C" __declspec(naked) void __stdcall EngMultiByteToWideChar_wrapper(){__asm{jmp mProcs[275*4]}}
extern "C" __declspec(naked) void __stdcall EngPaint_wrapper(){__asm{jmp mProcs[276*4]}}
extern "C" __declspec(naked) void __stdcall EngPlgBlt_wrapper(){__asm{jmp mProcs[277*4]}}
extern "C" __declspec(naked) void __stdcall EngQueryEMFInfo_wrapper(){__asm{jmp mProcs[278*4]}}
extern "C" __declspec(naked) void __stdcall EngQueryLocalTime_wrapper(){__asm{jmp mProcs[279*4]}}
extern "C" __declspec(naked) void __stdcall EngReleaseSemaphore_wrapper(){__asm{jmp mProcs[280*4]}}
extern "C" __declspec(naked) void __stdcall EngStretchBlt_wrapper(){__asm{jmp mProcs[281*4]}}
extern "C" __declspec(naked) void __stdcall EngStretchBltROP_wrapper(){__asm{jmp mProcs[282*4]}}
extern "C" __declspec(naked) void __stdcall EngStrokeAndFillPath_wrapper(){__asm{jmp mProcs[283*4]}}
extern "C" __declspec(naked) void __stdcall EngStrokePath_wrapper(){__asm{jmp mProcs[284*4]}}
extern "C" __declspec(naked) void __stdcall EngTextOut_wrapper(){__asm{jmp mProcs[285*4]}}
extern "C" __declspec(naked) void __stdcall EngTransparentBlt_wrapper(){__asm{jmp mProcs[286*4]}}
extern "C" __declspec(naked) void __stdcall EngUnicodeToMultiByteN_wrapper(){__asm{jmp mProcs[287*4]}}
extern "C" __declspec(naked) void __stdcall EngUnlockSurface_wrapper(){__asm{jmp mProcs[288*4]}}
extern "C" __declspec(naked) void __stdcall EngWideCharToMultiByte_wrapper(){__asm{jmp mProcs[289*4]}}
extern "C" __declspec(naked) void __stdcall EnumEnhMetaFile_wrapper(){__asm{jmp mProcs[290*4]}}
extern "C" __declspec(naked) void __stdcall EnumFontFamiliesA_wrapper(){__asm{jmp mProcs[291*4]}}
extern "C" __declspec(naked) void __stdcall EnumFontFamiliesExA_wrapper(){__asm{jmp mProcs[292*4]}}
extern "C" __declspec(naked) void __stdcall EnumFontFamiliesExW_wrapper(){__asm{jmp mProcs[293*4]}}
extern "C" __declspec(naked) void __stdcall EnumFontFamiliesW_wrapper(){__asm{jmp mProcs[294*4]}}
extern "C" __declspec(naked) void __stdcall EnumFontsA_wrapper(){__asm{jmp mProcs[295*4]}}
extern "C" __declspec(naked) void __stdcall EnumFontsW_wrapper(){__asm{jmp mProcs[296*4]}}
extern "C" __declspec(naked) void __stdcall EnumICMProfilesA_wrapper(){__asm{jmp mProcs[297*4]}}
extern "C" __declspec(naked) void __stdcall EnumICMProfilesW_wrapper(){__asm{jmp mProcs[298*4]}}
extern "C" __declspec(naked) void __stdcall EnumMetaFile_wrapper(){__asm{jmp mProcs[299*4]}}
extern "C" __declspec(naked) void __stdcall EnumObjects_wrapper(){__asm{jmp mProcs[300*4]}}
extern "C" __declspec(naked) void __stdcall EqualRgn_wrapper(){__asm{jmp mProcs[301*4]}}
extern "C" __declspec(naked) void __stdcall Escape_wrapper(){__asm{jmp mProcs[302*4]}}
extern "C" __declspec(naked) void __stdcall EudcLoadLinkW_wrapper(){__asm{jmp mProcs[303*4]}}
extern "C" __declspec(naked) void __stdcall EudcUnloadLinkW_wrapper(){__asm{jmp mProcs[304*4]}}
extern "C" __declspec(naked) void __stdcall ExcludeClipRect_wrapper(){__asm{jmp mProcs[305*4]}}
extern "C" __declspec(naked) void __stdcall ExtCreatePen_wrapper(){__asm{jmp mProcs[306*4]}}
extern "C" __declspec(naked) void __stdcall ExtCreateRegion_wrapper(){__asm{jmp mProcs[307*4]}}
extern "C" __declspec(naked) void __stdcall ExtEscape_wrapper(){__asm{jmp mProcs[308*4]}}
extern "C" __declspec(naked) void __stdcall ExtFloodFill_wrapper(){__asm{jmp mProcs[309*4]}}
extern "C" __declspec(naked) void __stdcall ExtSelectClipRgn_wrapper(){__asm{jmp mProcs[310*4]}}
extern "C" __declspec(naked) void __stdcall ExtTextOutA_wrapper(){__asm{jmp mProcs[311*4]}}
extern "C" __declspec(naked) void __stdcall ExtTextOutW_wrapper(){__asm{jmp mProcs[312*4]}}
extern "C" __declspec(naked) void __stdcall FONTOBJ_cGetAllGlyphHandles_wrapper(){__asm{jmp mProcs[313*4]}}
extern "C" __declspec(naked) void __stdcall FONTOBJ_cGetGlyphs_wrapper(){__asm{jmp mProcs[314*4]}}
extern "C" __declspec(naked) void __stdcall FONTOBJ_pQueryGlyphAttrs_wrapper(){__asm{jmp mProcs[315*4]}}
extern "C" __declspec(naked) void __stdcall FONTOBJ_pfdg_wrapper(){__asm{jmp mProcs[316*4]}}
extern "C" __declspec(naked) void __stdcall FONTOBJ_pifi_wrapper(){__asm{jmp mProcs[317*4]}}
extern "C" __declspec(naked) void __stdcall FONTOBJ_pvTrueTypeFontFile_wrapper(){__asm{jmp mProcs[318*4]}}
extern "C" __declspec(naked) void __stdcall FONTOBJ_pxoGetXform_wrapper(){__asm{jmp mProcs[319*4]}}
extern "C" __declspec(naked) void __stdcall FONTOBJ_vGetInfo_wrapper(){__asm{jmp mProcs[320*4]}}
extern "C" __declspec(naked) void __stdcall FillPath_wrapper(){__asm{jmp mProcs[321*4]}}
extern "C" __declspec(naked) void __stdcall FillRgn_wrapper(){__asm{jmp mProcs[322*4]}}
extern "C" __declspec(naked) void __stdcall FixBrushOrgEx_wrapper(){__asm{jmp mProcs[323*4]}}
extern "C" __declspec(naked) void __stdcall FlattenPath_wrapper(){__asm{jmp mProcs[324*4]}}
extern "C" __declspec(naked) void __stdcall FloodFill_wrapper(){__asm{jmp mProcs[325*4]}}
extern "C" __declspec(naked) void __stdcall FontIsLinked_wrapper(){__asm{jmp mProcs[326*4]}}
extern "C" __declspec(naked) void __stdcall FrameRgn_wrapper(){__asm{jmp mProcs[327*4]}}
extern "C" __declspec(naked) void __stdcall GdiAddFontResourceW_wrapper(){__asm{jmp mProcs[328*4]}}
extern "C" __declspec(naked) void __stdcall GdiAddGlsBounds_wrapper(){__asm{jmp mProcs[329*4]}}
extern "C" __declspec(naked) void __stdcall GdiAddGlsRecord_wrapper(){__asm{jmp mProcs[330*4]}}
extern "C" __declspec(naked) void __stdcall GdiAlphaBlend_wrapper(){__asm{jmp mProcs[331*4]}}
extern "C" __declspec(naked) void __stdcall GdiArtificialDecrementDriver_wrapper(){__asm{jmp mProcs[332*4]}}
extern "C" __declspec(naked) void __stdcall GdiCleanCacheDC_wrapper(){__asm{jmp mProcs[333*4]}}
extern "C" __declspec(naked) void __stdcall GdiComment_wrapper(){__asm{jmp mProcs[334*4]}}
extern "C" __declspec(naked) void __stdcall GdiConsoleTextOut_wrapper(){__asm{jmp mProcs[335*4]}}
extern "C" __declspec(naked) void __stdcall GdiConvertAndCheckDC_wrapper(){__asm{jmp mProcs[336*4]}}
extern "C" __declspec(naked) void __stdcall GdiConvertBitmap_wrapper(){__asm{jmp mProcs[337*4]}}
extern "C" __declspec(naked) void __stdcall GdiConvertBitmapV5_wrapper(){__asm{jmp mProcs[338*4]}}
extern "C" __declspec(naked) void __stdcall GdiConvertBrush_wrapper(){__asm{jmp mProcs[339*4]}}
extern "C" __declspec(naked) void __stdcall GdiConvertDC_wrapper(){__asm{jmp mProcs[340*4]}}
extern "C" __declspec(naked) void __stdcall GdiConvertEnhMetaFile_wrapper(){__asm{jmp mProcs[341*4]}}
extern "C" __declspec(naked) void __stdcall GdiConvertFont_wrapper(){__asm{jmp mProcs[342*4]}}
extern "C" __declspec(naked) void __stdcall GdiConvertMetaFilePict_wrapper(){__asm{jmp mProcs[343*4]}}
extern "C" __declspec(naked) void __stdcall GdiConvertPalette_wrapper(){__asm{jmp mProcs[344*4]}}
extern "C" __declspec(naked) void __stdcall GdiConvertRegion_wrapper(){__asm{jmp mProcs[345*4]}}
extern "C" __declspec(naked) void __stdcall GdiConvertToDevmodeW_wrapper(){__asm{jmp mProcs[346*4]}}
extern "C" __declspec(naked) void __stdcall GdiCreateLocalEnhMetaFile_wrapper(){__asm{jmp mProcs[347*4]}}
extern "C" __declspec(naked) void __stdcall GdiCreateLocalMetaFilePict_wrapper(){__asm{jmp mProcs[348*4]}}
extern "C" __declspec(naked) void __stdcall GdiDeleteLocalDC_wrapper(){__asm{jmp mProcs[349*4]}}
extern "C" __declspec(naked) void __stdcall GdiDeleteSpoolFileHandle_wrapper(){__asm{jmp mProcs[350*4]}}
extern "C" __declspec(naked) void __stdcall GdiDescribePixelFormat_wrapper(){__asm{jmp mProcs[351*4]}}
extern "C" __declspec(naked) void __stdcall GdiDllInitialize_wrapper(){__asm{jmp mProcs[352*4]}}
extern "C" __declspec(naked) void __stdcall GdiDrawStream_wrapper(){__asm{jmp mProcs[353*4]}}
extern "C" __declspec(naked) void __stdcall GdiEndDocEMF_wrapper(){__asm{jmp mProcs[354*4]}}
extern "C" __declspec(naked) void __stdcall GdiEndPageEMF_wrapper(){__asm{jmp mProcs[355*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry1_wrapper(){__asm{jmp mProcs[356*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry10_wrapper(){__asm{jmp mProcs[357*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry11_wrapper(){__asm{jmp mProcs[358*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry12_wrapper(){__asm{jmp mProcs[359*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry13_wrapper(){__asm{jmp mProcs[360*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry14_wrapper(){__asm{jmp mProcs[361*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry15_wrapper(){__asm{jmp mProcs[362*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry16_wrapper(){__asm{jmp mProcs[363*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry2_wrapper(){__asm{jmp mProcs[364*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry3_wrapper(){__asm{jmp mProcs[365*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry4_wrapper(){__asm{jmp mProcs[366*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry5_wrapper(){__asm{jmp mProcs[367*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry6_wrapper(){__asm{jmp mProcs[368*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry7_wrapper(){__asm{jmp mProcs[369*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry8_wrapper(){__asm{jmp mProcs[370*4]}}
extern "C" __declspec(naked) void __stdcall GdiEntry9_wrapper(){__asm{jmp mProcs[371*4]}}
extern "C" __declspec(naked) void __stdcall GdiFixUpHandle_wrapper(){__asm{jmp mProcs[372*4]}}
extern "C" __declspec(naked) void __stdcall GdiFlush_wrapper(){__asm{jmp mProcs[373*4]}}
extern "C" __declspec(naked) void __stdcall GdiFullscreenControl_wrapper(){__asm{jmp mProcs[374*4]}}
extern "C" __declspec(naked) void __stdcall GdiGetBatchLimit_wrapper(){__asm{jmp mProcs[375*4]}}
extern "C" __declspec(naked) void __stdcall GdiGetBitmapBitsSize_wrapper(){__asm{jmp mProcs[376*4]}}
extern "C" __declspec(naked) void __stdcall GdiGetCharDimensions_wrapper(){__asm{jmp mProcs[377*4]}}
extern "C" __declspec(naked) void __stdcall GdiGetCodePage_wrapper(){__asm{jmp mProcs[378*4]}}
extern "C" __declspec(naked) void __stdcall GdiGetDC_wrapper(){__asm{jmp mProcs[379*4]}}
extern "C" __declspec(naked) void __stdcall GdiGetDevmodeForPage_wrapper(){__asm{jmp mProcs[380*4]}}
extern "C" __declspec(naked) void __stdcall GdiGetLocalBrush_wrapper(){__asm{jmp mProcs[381*4]}}
extern "C" __declspec(naked) void __stdcall GdiGetLocalDC_wrapper(){__asm{jmp mProcs[382*4]}}
extern "C" __declspec(naked) void __stdcall GdiGetLocalFont_wrapper(){__asm{jmp mProcs[383*4]}}
extern "C" __declspec(naked) void __stdcall GdiGetPageCount_wrapper(){__asm{jmp mProcs[384*4]}}
extern "C" __declspec(naked) void __stdcall GdiGetPageHandle_wrapper(){__asm{jmp mProcs[385*4]}}
extern "C" __declspec(naked) void __stdcall GdiGetSpoolFileHandle_wrapper(){__asm{jmp mProcs[386*4]}}
extern "C" __declspec(naked) void __stdcall GdiGetSpoolMessage_wrapper(){__asm{jmp mProcs[387*4]}}
extern "C" __declspec(naked) void __stdcall GdiGradientFill_wrapper(){__asm{jmp mProcs[388*4]}}
extern "C" __declspec(naked) void __stdcall GdiInitSpool_wrapper(){__asm{jmp mProcs[389*4]}}
extern "C" __declspec(naked) void __stdcall GdiInitializeLanguagePack_wrapper(){__asm{jmp mProcs[390*4]}}
extern "C" __declspec(naked) void __stdcall GdiIsMetaFileDC_wrapper(){__asm{jmp mProcs[391*4]}}
extern "C" __declspec(naked) void __stdcall GdiIsMetaPrintDC_wrapper(){__asm{jmp mProcs[392*4]}}
extern "C" __declspec(naked) void __stdcall GdiIsPlayMetafileDC_wrapper(){__asm{jmp mProcs[393*4]}}
extern "C" __declspec(naked) void __stdcall GdiIsScreenDC_wrapper(){__asm{jmp mProcs[394*4]}}
extern "C" __declspec(naked) void __stdcall GdiLoadType1Fonts_wrapper(){__asm{jmp mProcs[395*4]}}
extern "C" __declspec(naked) void __stdcall GdiPlayDCScript_wrapper(){__asm{jmp mProcs[396*4]}}
extern "C" __declspec(naked) void __stdcall GdiPlayEMF_wrapper(){__asm{jmp mProcs[397*4]}}
extern "C" __declspec(naked) void __stdcall GdiPlayJournal_wrapper(){__asm{jmp mProcs[398*4]}}
extern "C" __declspec(naked) void __stdcall GdiPlayPageEMF_wrapper(){__asm{jmp mProcs[399*4]}}
extern "C" __declspec(naked) void __stdcall GdiPlayPrivatePageEMF_wrapper(){__asm{jmp mProcs[400*4]}}
extern "C" __declspec(naked) void __stdcall GdiPlayScript_wrapper(){__asm{jmp mProcs[401*4]}}
extern "C" __declspec(naked) void __stdcall GdiPrinterThunk_wrapper(){__asm{jmp mProcs[402*4]}}
extern "C" __declspec(naked) void __stdcall GdiProcessSetup_wrapper(){__asm{jmp mProcs[403*4]}}
extern "C" __declspec(naked) void __stdcall GdiQueryFonts_wrapper(){__asm{jmp mProcs[404*4]}}
extern "C" __declspec(naked) void __stdcall GdiQueryTable_wrapper(){__asm{jmp mProcs[405*4]}}
extern "C" __declspec(naked) void __stdcall GdiRealizationInfo_wrapper(){__asm{jmp mProcs[406*4]}}
extern "C" __declspec(naked) void __stdcall GdiReleaseDC_wrapper(){__asm{jmp mProcs[407*4]}}
extern "C" __declspec(naked) void __stdcall GdiReleaseLocalDC_wrapper(){__asm{jmp mProcs[408*4]}}
extern "C" __declspec(naked) void __stdcall GdiResetDCEMF_wrapper(){__asm{jmp mProcs[409*4]}}
extern "C" __declspec(naked) void __stdcall GdiSetAttrs_wrapper(){__asm{jmp mProcs[410*4]}}
extern "C" __declspec(naked) void __stdcall GdiSetBatchLimit_wrapper(){__asm{jmp mProcs[411*4]}}
extern "C" __declspec(naked) void __stdcall GdiSetLastError_wrapper(){__asm{jmp mProcs[412*4]}}
extern "C" __declspec(naked) void __stdcall GdiSetPixelFormat_wrapper(){__asm{jmp mProcs[413*4]}}
extern "C" __declspec(naked) void __stdcall GdiSetServerAttr_wrapper(){__asm{jmp mProcs[414*4]}}
extern "C" __declspec(naked) void __stdcall GdiStartDocEMF_wrapper(){__asm{jmp mProcs[415*4]}}
extern "C" __declspec(naked) void __stdcall GdiStartPageEMF_wrapper(){__asm{jmp mProcs[416*4]}}
extern "C" __declspec(naked) void __stdcall GdiSwapBuffers_wrapper(){__asm{jmp mProcs[417*4]}}
extern "C" __declspec(naked) void __stdcall GdiTransparentBlt_wrapper(){__asm{jmp mProcs[418*4]}}
extern "C" __declspec(naked) void __stdcall GdiValidateHandle_wrapper(){__asm{jmp mProcs[419*4]}}
extern "C" __declspec(naked) void __stdcall GetArcDirection_wrapper(){__asm{jmp mProcs[420*4]}}
extern "C" __declspec(naked) void __stdcall GetAspectRatioFilterEx_wrapper(){__asm{jmp mProcs[421*4]}}
extern "C" __declspec(naked) void __stdcall GetBitmapAttributes_wrapper(){__asm{jmp mProcs[422*4]}}
extern "C" __declspec(naked) void __stdcall GetBitmapBits_wrapper(){__asm{jmp mProcs[423*4]}}
extern "C" __declspec(naked) void __stdcall GetBitmapDimensionEx_wrapper(){__asm{jmp mProcs[424*4]}}
extern "C" __declspec(naked) void __stdcall GetBkColor_wrapper(){__asm{jmp mProcs[425*4]}}
extern "C" __declspec(naked) void __stdcall GetBkMode_wrapper(){__asm{jmp mProcs[426*4]}}
extern "C" __declspec(naked) void __stdcall GetBoundsRect_wrapper(){__asm{jmp mProcs[427*4]}}
extern "C" __declspec(naked) void __stdcall GetBrushAttributes_wrapper(){__asm{jmp mProcs[428*4]}}
extern "C" __declspec(naked) void __stdcall GetBrushOrgEx_wrapper(){__asm{jmp mProcs[429*4]}}
extern "C" __declspec(naked) void __stdcall GetCOPPCompatibleOPMInformation_wrapper(){__asm{jmp mProcs[430*4]}}
extern "C" __declspec(naked) void __stdcall GetCertificate_wrapper(){__asm{jmp mProcs[431*4]}}
extern "C" __declspec(naked) void __stdcall GetCertificateSize_wrapper(){__asm{jmp mProcs[432*4]}}
extern "C" __declspec(naked) void __stdcall GetCharABCWidthsA_wrapper(){__asm{jmp mProcs[433*4]}}
extern "C" __declspec(naked) void __stdcall GetCharABCWidthsFloatA_wrapper(){__asm{jmp mProcs[434*4]}}
extern "C" __declspec(naked) void __stdcall GetCharABCWidthsFloatW_wrapper(){__asm{jmp mProcs[435*4]}}
extern "C" __declspec(naked) void __stdcall GetCharABCWidthsI_wrapper(){__asm{jmp mProcs[436*4]}}
extern "C" __declspec(naked) void __stdcall GetCharABCWidthsW_wrapper(){__asm{jmp mProcs[437*4]}}
extern "C" __declspec(naked) void __stdcall GetCharWidth32A_wrapper(){__asm{jmp mProcs[438*4]}}
extern "C" __declspec(naked) void __stdcall GetCharWidth32W_wrapper(){__asm{jmp mProcs[439*4]}}
extern "C" __declspec(naked) void __stdcall GetCharWidthA_wrapper(){__asm{jmp mProcs[440*4]}}
extern "C" __declspec(naked) void __stdcall GetCharWidthFloatA_wrapper(){__asm{jmp mProcs[441*4]}}
extern "C" __declspec(naked) void __stdcall GetCharWidthFloatW_wrapper(){__asm{jmp mProcs[442*4]}}
extern "C" __declspec(naked) void __stdcall GetCharWidthI_wrapper(){__asm{jmp mProcs[443*4]}}
extern "C" __declspec(naked) void __stdcall GetCharWidthInfo_wrapper(){__asm{jmp mProcs[444*4]}}
extern "C" __declspec(naked) void __stdcall GetCharWidthW_wrapper(){__asm{jmp mProcs[445*4]}}
extern "C" __declspec(naked) void __stdcall GetCharacterPlacementA_wrapper(){__asm{jmp mProcs[446*4]}}
extern "C" __declspec(naked) void __stdcall GetCharacterPlacementW_wrapper(){__asm{jmp mProcs[447*4]}}
extern "C" __declspec(naked) void __stdcall GetClipBox_wrapper(){__asm{jmp mProcs[448*4]}}
extern "C" __declspec(naked) void __stdcall GetClipRgn_wrapper(){__asm{jmp mProcs[449*4]}}
extern "C" __declspec(naked) void __stdcall GetColorAdjustment_wrapper(){__asm{jmp mProcs[450*4]}}
extern "C" __declspec(naked) void __stdcall GetColorSpace_wrapper(){__asm{jmp mProcs[451*4]}}
extern "C" __declspec(naked) void __stdcall GetCurrentObject_wrapper(){__asm{jmp mProcs[452*4]}}
extern "C" __declspec(naked) void __stdcall GetCurrentPositionEx_wrapper(){__asm{jmp mProcs[453*4]}}
extern "C" __declspec(naked) void __stdcall GetDCBrushColor_wrapper(){__asm{jmp mProcs[454*4]}}
extern "C" __declspec(naked) void __stdcall GetDCOrgEx_wrapper(){__asm{jmp mProcs[455*4]}}
extern "C" __declspec(naked) void __stdcall GetDCPenColor_wrapper(){__asm{jmp mProcs[456*4]}}
extern "C" __declspec(naked) void __stdcall GetDIBColorTable_wrapper(){__asm{jmp mProcs[457*4]}}
extern "C" __declspec(naked) void __stdcall GetDIBits_wrapper(){__asm{jmp mProcs[458*4]}}
extern "C" __declspec(naked) void __stdcall GetDeviceCaps_wrapper(){__asm{jmp mProcs[459*4]}}
extern "C" __declspec(naked) void __stdcall GetDeviceGammaRamp_wrapper(){__asm{jmp mProcs[460*4]}}
extern "C" __declspec(naked) void __stdcall GetETM_wrapper(){__asm{jmp mProcs[461*4]}}
extern "C" __declspec(naked) void __stdcall GetEUDCTimeStamp_wrapper(){__asm{jmp mProcs[462*4]}}
extern "C" __declspec(naked) void __stdcall GetEUDCTimeStampExW_wrapper(){__asm{jmp mProcs[463*4]}}
extern "C" __declspec(naked) void __stdcall GetEnhMetaFileA_wrapper(){__asm{jmp mProcs[464*4]}}
extern "C" __declspec(naked) void __stdcall GetEnhMetaFileBits_wrapper(){__asm{jmp mProcs[465*4]}}
extern "C" __declspec(naked) void __stdcall GetEnhMetaFileDescriptionA_wrapper(){__asm{jmp mProcs[466*4]}}
extern "C" __declspec(naked) void __stdcall GetEnhMetaFileDescriptionW_wrapper(){__asm{jmp mProcs[467*4]}}
extern "C" __declspec(naked) void __stdcall GetEnhMetaFileHeader_wrapper(){__asm{jmp mProcs[468*4]}}
extern "C" __declspec(naked) void __stdcall GetEnhMetaFilePaletteEntries_wrapper(){__asm{jmp mProcs[469*4]}}
extern "C" __declspec(naked) void __stdcall GetEnhMetaFilePixelFormat_wrapper(){__asm{jmp mProcs[470*4]}}
extern "C" __declspec(naked) void __stdcall GetEnhMetaFileW_wrapper(){__asm{jmp mProcs[471*4]}}
extern "C" __declspec(naked) void __stdcall GetFontAssocStatus_wrapper(){__asm{jmp mProcs[472*4]}}
extern "C" __declspec(naked) void __stdcall GetFontData_wrapper(){__asm{jmp mProcs[473*4]}}
extern "C" __declspec(naked) void __stdcall GetFontFileData_wrapper(){__asm{jmp mProcs[474*4]}}
extern "C" __declspec(naked) void __stdcall GetFontFileInfo_wrapper(){__asm{jmp mProcs[475*4]}}
extern "C" __declspec(naked) void __stdcall GetFontLanguageInfo_wrapper(){__asm{jmp mProcs[476*4]}}
extern "C" __declspec(naked) void __stdcall GetFontRealizationInfo_wrapper(){__asm{jmp mProcs[477*4]}}
extern "C" __declspec(naked) void __stdcall GetFontResourceInfoW_wrapper(){__asm{jmp mProcs[478*4]}}
extern "C" __declspec(naked) void __stdcall GetFontUnicodeRanges_wrapper(){__asm{jmp mProcs[479*4]}}
extern "C" __declspec(naked) void __stdcall GetGlyphIndicesA_wrapper(){__asm{jmp mProcs[480*4]}}
extern "C" __declspec(naked) void __stdcall GetGlyphIndicesW_wrapper(){__asm{jmp mProcs[481*4]}}
extern "C" __declspec(naked) void __stdcall GetGlyphOutline_wrapper(){__asm{jmp mProcs[482*4]}}
extern "C" __declspec(naked) void __stdcall GetGlyphOutlineA_wrapper(){__asm{jmp mProcs[483*4]}}
extern "C" __declspec(naked) void __stdcall GetGlyphOutlineW_wrapper(){__asm{jmp mProcs[484*4]}}
extern "C" __declspec(naked) void __stdcall GetGlyphOutlineWow_wrapper(){__asm{jmp mProcs[485*4]}}
extern "C" __declspec(naked) void __stdcall GetGraphicsMode_wrapper(){__asm{jmp mProcs[486*4]}}
extern "C" __declspec(naked) void __stdcall GetHFONT_wrapper(){__asm{jmp mProcs[487*4]}}
extern "C" __declspec(naked) void __stdcall GetICMProfileA_wrapper(){__asm{jmp mProcs[488*4]}}
extern "C" __declspec(naked) void __stdcall GetICMProfileW_wrapper(){__asm{jmp mProcs[489*4]}}
extern "C" __declspec(naked) void __stdcall GetKerningPairs_wrapper(){__asm{jmp mProcs[490*4]}}
extern "C" __declspec(naked) void __stdcall GetKerningPairsA_wrapper(){__asm{jmp mProcs[491*4]}}
extern "C" __declspec(naked) void __stdcall GetKerningPairsW_wrapper(){__asm{jmp mProcs[492*4]}}
extern "C" __declspec(naked) void __stdcall GetLayout_wrapper(){__asm{jmp mProcs[493*4]}}
extern "C" __declspec(naked) void __stdcall GetLogColorSpaceA_wrapper(){__asm{jmp mProcs[494*4]}}
extern "C" __declspec(naked) void __stdcall GetLogColorSpaceW_wrapper(){__asm{jmp mProcs[495*4]}}
extern "C" __declspec(naked) void __stdcall GetMapMode_wrapper(){__asm{jmp mProcs[496*4]}}
extern "C" __declspec(naked) void __stdcall GetMetaFileA_wrapper(){__asm{jmp mProcs[497*4]}}
extern "C" __declspec(naked) void __stdcall GetMetaFileBitsEx_wrapper(){__asm{jmp mProcs[498*4]}}
extern "C" __declspec(naked) void __stdcall GetMetaFileW_wrapper(){__asm{jmp mProcs[499*4]}}
extern "C" __declspec(naked) void __stdcall GetMetaRgn_wrapper(){__asm{jmp mProcs[500*4]}}
extern "C" __declspec(naked) void __stdcall GetMiterLimit_wrapper(){__asm{jmp mProcs[501*4]}}
extern "C" __declspec(naked) void __stdcall GetNearestColor_wrapper(){__asm{jmp mProcs[502*4]}}
extern "C" __declspec(naked) void __stdcall GetNearestPaletteIndex_wrapper(){__asm{jmp mProcs[503*4]}}
extern "C" __declspec(naked) void __stdcall GetNumberOfPhysicalMonitors_wrapper(){__asm{jmp mProcs[504*4]}}
extern "C" __declspec(naked) void __stdcall GetOPMInformation_wrapper(){__asm{jmp mProcs[505*4]}}
extern "C" __declspec(naked) void __stdcall GetOPMRandomNumber_wrapper(){__asm{jmp mProcs[506*4]}}
extern "C" __declspec(naked) void __stdcall GetObjectA_wrapper(){__asm{jmp mProcs[507*4]}}
extern "C" __declspec(naked) void __stdcall GetObjectType_wrapper(){__asm{jmp mProcs[508*4]}}
extern "C" __declspec(naked) void __stdcall GetObjectW_wrapper(){__asm{jmp mProcs[509*4]}}
extern "C" __declspec(naked) void __stdcall GetOutlineTextMetricsA_wrapper(){__asm{jmp mProcs[510*4]}}
extern "C" __declspec(naked) void __stdcall GetOutlineTextMetricsW_wrapper(){__asm{jmp mProcs[511*4]}}
extern "C" __declspec(naked) void __stdcall GetPaletteEntries_wrapper(){__asm{jmp mProcs[512*4]}}
extern "C" __declspec(naked) void __stdcall GetPath_wrapper(){__asm{jmp mProcs[513*4]}}
extern "C" __declspec(naked) void __stdcall GetPhysicalMonitorDescription_wrapper(){__asm{jmp mProcs[514*4]}}
extern "C" __declspec(naked) void __stdcall GetPhysicalMonitors_wrapper(){__asm{jmp mProcs[515*4]}}
extern "C" __declspec(naked) void __stdcall GetPixel_wrapper(){__asm{jmp mProcs[516*4]}}
extern "C" __declspec(naked) void __stdcall GetPixelFormat_wrapper(){__asm{jmp mProcs[517*4]}}
extern "C" __declspec(naked) void __stdcall GetPolyFillMode_wrapper(){__asm{jmp mProcs[518*4]}}
extern "C" __declspec(naked) void __stdcall GetROP2_wrapper(){__asm{jmp mProcs[519*4]}}
extern "C" __declspec(naked) void __stdcall GetRandomRgn_wrapper(){__asm{jmp mProcs[520*4]}}
extern "C" __declspec(naked) void __stdcall GetRasterizerCaps_wrapper(){__asm{jmp mProcs[521*4]}}
extern "C" __declspec(naked) void __stdcall GetRegionData_wrapper(){__asm{jmp mProcs[522*4]}}
extern "C" __declspec(naked) void __stdcall GetRelAbs_wrapper(){__asm{jmp mProcs[523*4]}}
extern "C" __declspec(naked) void __stdcall GetRgnBox_wrapper(){__asm{jmp mProcs[524*4]}}
extern "C" __declspec(naked) void __stdcall GetStockObject_wrapper(){__asm{jmp mProcs[525*4]}}
extern "C" __declspec(naked) void __stdcall GetStretchBltMode_wrapper(){__asm{jmp mProcs[526*4]}}
extern "C" __declspec(naked) void __stdcall GetStringBitmapA_wrapper(){__asm{jmp mProcs[527*4]}}
extern "C" __declspec(naked) void __stdcall GetStringBitmapW_wrapper(){__asm{jmp mProcs[528*4]}}
extern "C" __declspec(naked) void __stdcall GetSuggestedOPMProtectedOutputArraySize_wrapper(){__asm{jmp mProcs[529*4]}}
extern "C" __declspec(naked) void __stdcall GetSystemPaletteEntries_wrapper(){__asm{jmp mProcs[530*4]}}
extern "C" __declspec(naked) void __stdcall GetSystemPaletteUse_wrapper(){__asm{jmp mProcs[531*4]}}
extern "C" __declspec(naked) void __stdcall GetTextAlign_wrapper(){__asm{jmp mProcs[532*4]}}
extern "C" __declspec(naked) void __stdcall GetTextCharacterExtra_wrapper(){__asm{jmp mProcs[533*4]}}
extern "C" __declspec(naked) void __stdcall GetTextCharset_wrapper(){__asm{jmp mProcs[534*4]}}
extern "C" __declspec(naked) void __stdcall GetTextCharsetInfo_wrapper(){__asm{jmp mProcs[535*4]}}
extern "C" __declspec(naked) void __stdcall GetTextColor_wrapper(){__asm{jmp mProcs[536*4]}}
extern "C" __declspec(naked) void __stdcall GetTextExtentExPointA_wrapper(){__asm{jmp mProcs[537*4]}}
extern "C" __declspec(naked) void __stdcall GetTextExtentExPointI_wrapper(){__asm{jmp mProcs[538*4]}}
extern "C" __declspec(naked) void __stdcall GetTextExtentExPointW_wrapper(){__asm{jmp mProcs[539*4]}}
extern "C" __declspec(naked) void __stdcall GetTextExtentExPointWPri_wrapper(){__asm{jmp mProcs[540*4]}}
extern "C" __declspec(naked) void __stdcall GetTextExtentPoint32A_wrapper(){__asm{jmp mProcs[541*4]}}
extern "C" __declspec(naked) void __stdcall GetTextExtentPoint32W_wrapper(){__asm{jmp mProcs[542*4]}}
extern "C" __declspec(naked) void __stdcall GetTextExtentPointA_wrapper(){__asm{jmp mProcs[543*4]}}
extern "C" __declspec(naked) void __stdcall GetTextExtentPointI_wrapper(){__asm{jmp mProcs[544*4]}}
extern "C" __declspec(naked) void __stdcall GetTextExtentPointW_wrapper(){__asm{jmp mProcs[545*4]}}
extern "C" __declspec(naked) void __stdcall GetTextFaceA_wrapper(){__asm{jmp mProcs[546*4]}}
extern "C" __declspec(naked) void __stdcall GetTextFaceAliasW_wrapper(){__asm{jmp mProcs[547*4]}}
extern "C" __declspec(naked) void __stdcall GetTextFaceW_wrapper(){__asm{jmp mProcs[548*4]}}
extern "C" __declspec(naked) void __stdcall GetTextMetricsA_wrapper(){__asm{jmp mProcs[549*4]}}
extern "C" __declspec(naked) void __stdcall GetTextMetricsW_wrapper(){__asm{jmp mProcs[550*4]}}
extern "C" __declspec(naked) void __stdcall GetTransform_wrapper(){__asm{jmp mProcs[551*4]}}
extern "C" __declspec(naked) void __stdcall GetViewportExtEx_wrapper(){__asm{jmp mProcs[552*4]}}
extern "C" __declspec(naked) void __stdcall GetViewportOrgEx_wrapper(){__asm{jmp mProcs[553*4]}}
extern "C" __declspec(naked) void __stdcall GetWinMetaFileBits_wrapper(){__asm{jmp mProcs[554*4]}}
extern "C" __declspec(naked) void __stdcall GetWindowExtEx_wrapper(){__asm{jmp mProcs[555*4]}}
extern "C" __declspec(naked) void __stdcall GetWindowOrgEx_wrapper(){__asm{jmp mProcs[556*4]}}
extern "C" __declspec(naked) void __stdcall GetWorldTransform_wrapper(){__asm{jmp mProcs[557*4]}}
extern "C" __declspec(naked) void __stdcall HT_Get8BPPFormatPalette_wrapper(){__asm{jmp mProcs[558*4]}}
extern "C" __declspec(naked) void __stdcall HT_Get8BPPMaskPalette_wrapper(){__asm{jmp mProcs[559*4]}}
extern "C" __declspec(naked) void __stdcall IntersectClipRect_wrapper(){__asm{jmp mProcs[560*4]}}
extern "C" __declspec(naked) void __stdcall InvertRgn_wrapper(){__asm{jmp mProcs[561*4]}}
extern "C" __declspec(naked) void __stdcall IsValidEnhMetaRecord_wrapper(){__asm{jmp mProcs[562*4]}}
extern "C" __declspec(naked) void __stdcall IsValidEnhMetaRecordOffExt_wrapper(){__asm{jmp mProcs[563*4]}}
extern "C" __declspec(naked) void __stdcall LPtoDP_wrapper(){__asm{jmp mProcs[564*4]}}
extern "C" __declspec(naked) void __stdcall LineDDA_wrapper(){__asm{jmp mProcs[565*4]}}
extern "C" __declspec(naked) void __stdcall LineTo_wrapper(){__asm{jmp mProcs[566*4]}}
extern "C" __declspec(naked) void __stdcall MaskBlt_wrapper(){__asm{jmp mProcs[567*4]}}
extern "C" __declspec(naked) void __stdcall MirrorRgn_wrapper(){__asm{jmp mProcs[568*4]}}
extern "C" __declspec(naked) void __stdcall ModifyWorldTransform_wrapper(){__asm{jmp mProcs[569*4]}}
extern "C" __declspec(naked) void __stdcall MoveToEx_wrapper(){__asm{jmp mProcs[570*4]}}
extern "C" __declspec(naked) void __stdcall NamedEscape_wrapper(){__asm{jmp mProcs[571*4]}}
extern "C" __declspec(naked) void __stdcall OffsetClipRgn_wrapper(){__asm{jmp mProcs[572*4]}}
extern "C" __declspec(naked) void __stdcall OffsetRgn_wrapper(){__asm{jmp mProcs[573*4]}}
extern "C" __declspec(naked) void __stdcall OffsetViewportOrgEx_wrapper(){__asm{jmp mProcs[574*4]}}
extern "C" __declspec(naked) void __stdcall OffsetWindowOrgEx_wrapper(){__asm{jmp mProcs[575*4]}}
extern "C" __declspec(naked) void __stdcall PATHOBJ_bEnum_wrapper(){__asm{jmp mProcs[576*4]}}
extern "C" __declspec(naked) void __stdcall PATHOBJ_bEnumClipLines_wrapper(){__asm{jmp mProcs[577*4]}}
extern "C" __declspec(naked) void __stdcall PATHOBJ_vEnumStart_wrapper(){__asm{jmp mProcs[578*4]}}
extern "C" __declspec(naked) void __stdcall PATHOBJ_vEnumStartClipLines_wrapper(){__asm{jmp mProcs[579*4]}}
extern "C" __declspec(naked) void __stdcall PATHOBJ_vGetBounds_wrapper(){__asm{jmp mProcs[580*4]}}
extern "C" __declspec(naked) void __stdcall PaintRgn_wrapper(){__asm{jmp mProcs[581*4]}}
extern "C" __declspec(naked) void __stdcall PatBlt_wrapper(){__asm{jmp mProcs[582*4]}}
extern "C" __declspec(naked) void __stdcall PathToRegion_wrapper(){__asm{jmp mProcs[583*4]}}
extern "C" __declspec(naked) void __stdcall Pie_wrapper(){__asm{jmp mProcs[584*4]}}
extern "C" __declspec(naked) void __stdcall PlayEnhMetaFile_wrapper(){__asm{jmp mProcs[585*4]}}
extern "C" __declspec(naked) void __stdcall PlayEnhMetaFileRecord_wrapper(){__asm{jmp mProcs[586*4]}}
extern "C" __declspec(naked) void __stdcall PlayMetaFile_wrapper(){__asm{jmp mProcs[587*4]}}
extern "C" __declspec(naked) void __stdcall PlayMetaFileRecord_wrapper(){__asm{jmp mProcs[588*4]}}
extern "C" __declspec(naked) void __stdcall PlgBlt_wrapper(){__asm{jmp mProcs[589*4]}}
extern "C" __declspec(naked) void __stdcall PolyBezier_wrapper(){__asm{jmp mProcs[590*4]}}
extern "C" __declspec(naked) void __stdcall PolyBezierTo_wrapper(){__asm{jmp mProcs[591*4]}}
extern "C" __declspec(naked) void __stdcall PolyDraw_wrapper(){__asm{jmp mProcs[592*4]}}
extern "C" __declspec(naked) void __stdcall PolyPatBlt_wrapper(){__asm{jmp mProcs[593*4]}}
extern "C" __declspec(naked) void __stdcall PolyPolygon_wrapper(){__asm{jmp mProcs[594*4]}}
extern "C" __declspec(naked) void __stdcall PolyPolyline_wrapper(){__asm{jmp mProcs[595*4]}}
extern "C" __declspec(naked) void __stdcall PolyTextOutA_wrapper(){__asm{jmp mProcs[596*4]}}
extern "C" __declspec(naked) void __stdcall PolyTextOutW_wrapper(){__asm{jmp mProcs[597*4]}}
extern "C" __declspec(naked) void __stdcall Polygon_wrapper(){__asm{jmp mProcs[598*4]}}
extern "C" __declspec(naked) void __stdcall Polyline_wrapper(){__asm{jmp mProcs[599*4]}}
extern "C" __declspec(naked) void __stdcall PolylineTo_wrapper(){__asm{jmp mProcs[600*4]}}
extern "C" __declspec(naked) void __stdcall PtInRegion_wrapper(){__asm{jmp mProcs[601*4]}}
extern "C" __declspec(naked) void __stdcall PtVisible_wrapper(){__asm{jmp mProcs[602*4]}}
extern "C" __declspec(naked) void __stdcall QueryFontAssocStatus_wrapper(){__asm{jmp mProcs[603*4]}}
extern "C" __declspec(naked) void __stdcall RealizePalette_wrapper(){__asm{jmp mProcs[604*4]}}
extern "C" __declspec(naked) void __stdcall RectInRegion_wrapper(){__asm{jmp mProcs[605*4]}}
extern "C" __declspec(naked) void __stdcall RectVisible_wrapper(){__asm{jmp mProcs[606*4]}}
extern "C" __declspec(naked) void __stdcall Rectangle_wrapper(){__asm{jmp mProcs[607*4]}}
extern "C" __declspec(naked) void __stdcall RemoveFontMemResourceEx_wrapper(){__asm{jmp mProcs[608*4]}}
extern "C" __declspec(naked) void __stdcall RemoveFontResourceA_wrapper(){__asm{jmp mProcs[609*4]}}
extern "C" __declspec(naked) void __stdcall RemoveFontResourceExA_wrapper(){__asm{jmp mProcs[610*4]}}
extern "C" __declspec(naked) void __stdcall RemoveFontResourceExW_wrapper(){__asm{jmp mProcs[611*4]}}
extern "C" __declspec(naked) void __stdcall RemoveFontResourceTracking_wrapper(){__asm{jmp mProcs[612*4]}}
extern "C" __declspec(naked) void __stdcall RemoveFontResourceW_wrapper(){__asm{jmp mProcs[613*4]}}
extern "C" __declspec(naked) void __stdcall ResetDCA_wrapper(){__asm{jmp mProcs[614*4]}}
extern "C" __declspec(naked) void __stdcall ResetDCW_wrapper(){__asm{jmp mProcs[615*4]}}
extern "C" __declspec(naked) void __stdcall ResizePalette_wrapper(){__asm{jmp mProcs[616*4]}}
extern "C" __declspec(naked) void __stdcall RestoreDC_wrapper(){__asm{jmp mProcs[617*4]}}
extern "C" __declspec(naked) void __stdcall RoundRect_wrapper(){__asm{jmp mProcs[618*4]}}
extern "C" __declspec(naked) void __stdcall STROBJ_bEnum_wrapper(){__asm{jmp mProcs[619*4]}}
extern "C" __declspec(naked) void __stdcall STROBJ_bEnumPositionsOnly_wrapper(){__asm{jmp mProcs[620*4]}}
extern "C" __declspec(naked) void __stdcall STROBJ_bGetAdvanceWidths_wrapper(){__asm{jmp mProcs[621*4]}}
extern "C" __declspec(naked) void __stdcall STROBJ_dwGetCodePage_wrapper(){__asm{jmp mProcs[622*4]}}
extern "C" __declspec(naked) void __stdcall STROBJ_vEnumStart_wrapper(){__asm{jmp mProcs[623*4]}}
extern "C" __declspec(naked) void __stdcall SaveDC_wrapper(){__asm{jmp mProcs[624*4]}}
extern "C" __declspec(naked) void __stdcall ScaleViewportExtEx_wrapper(){__asm{jmp mProcs[625*4]}}
extern "C" __declspec(naked) void __stdcall ScaleWindowExtEx_wrapper(){__asm{jmp mProcs[626*4]}}
extern "C" __declspec(naked) void __stdcall SelectBrushLocal_wrapper(){__asm{jmp mProcs[627*4]}}
extern "C" __declspec(naked) void __stdcall SelectClipPath_wrapper(){__asm{jmp mProcs[628*4]}}
extern "C" __declspec(naked) void __stdcall SelectClipRgn_wrapper(){__asm{jmp mProcs[629*4]}}
extern "C" __declspec(naked) void __stdcall SelectFontLocal_wrapper(){__asm{jmp mProcs[630*4]}}
extern "C" __declspec(naked) void __stdcall SelectObject_wrapper(){__asm{jmp mProcs[631*4]}}
extern "C" __declspec(naked) void __stdcall SelectPalette_wrapper(){__asm{jmp mProcs[632*4]}}
extern "C" __declspec(naked) void __stdcall SetAbortProc_wrapper(){__asm{jmp mProcs[633*4]}}
extern "C" __declspec(naked) void __stdcall SetArcDirection_wrapper(){__asm{jmp mProcs[634*4]}}
extern "C" __declspec(naked) void __stdcall SetBitmapAttributes_wrapper(){__asm{jmp mProcs[635*4]}}
extern "C" __declspec(naked) void __stdcall SetBitmapBits_wrapper(){__asm{jmp mProcs[636*4]}}
extern "C" __declspec(naked) void __stdcall SetBitmapDimensionEx_wrapper(){__asm{jmp mProcs[637*4]}}
extern "C" __declspec(naked) void __stdcall SetBkColor_wrapper(){__asm{jmp mProcs[638*4]}}
extern "C" __declspec(naked) void __stdcall SetBkMode_wrapper(){__asm{jmp mProcs[639*4]}}
extern "C" __declspec(naked) void __stdcall SetBoundsRect_wrapper(){__asm{jmp mProcs[640*4]}}
extern "C" __declspec(naked) void __stdcall SetBrushAttributes_wrapper(){__asm{jmp mProcs[641*4]}}
extern "C" __declspec(naked) void __stdcall SetBrushOrgEx_wrapper(){__asm{jmp mProcs[642*4]}}
extern "C" __declspec(naked) void __stdcall SetColorAdjustment_wrapper(){__asm{jmp mProcs[643*4]}}
extern "C" __declspec(naked) void __stdcall SetColorSpace_wrapper(){__asm{jmp mProcs[644*4]}}
extern "C" __declspec(naked) void __stdcall SetDCBrushColor_wrapper(){__asm{jmp mProcs[645*4]}}
extern "C" __declspec(naked) void __stdcall SetDCPenColor_wrapper(){__asm{jmp mProcs[646*4]}}
extern "C" __declspec(naked) void __stdcall SetDIBColorTable_wrapper(){__asm{jmp mProcs[647*4]}}
extern "C" __declspec(naked) void __stdcall SetDIBits_wrapper(){__asm{jmp mProcs[648*4]}}
extern "C" __declspec(naked) void __stdcall SetDIBitsToDevice_wrapper(){__asm{jmp mProcs[649*4]}}
extern "C" __declspec(naked) void __stdcall SetDeviceGammaRamp_wrapper(){__asm{jmp mProcs[650*4]}}
extern "C" __declspec(naked) void __stdcall SetEnhMetaFileBits_wrapper(){__asm{jmp mProcs[651*4]}}
extern "C" __declspec(naked) void __stdcall SetFontEnumeration_wrapper(){__asm{jmp mProcs[652*4]}}
extern "C" __declspec(naked) void __stdcall SetGraphicsMode_wrapper(){__asm{jmp mProcs[653*4]}}
extern "C" __declspec(naked) void __stdcall SetICMMode_wrapper(){__asm{jmp mProcs[654*4]}}
extern "C" __declspec(naked) void __stdcall SetICMProfileA_wrapper(){__asm{jmp mProcs[655*4]}}
extern "C" __declspec(naked) void __stdcall SetICMProfileW_wrapper(){__asm{jmp mProcs[656*4]}}
extern "C" __declspec(naked) void __stdcall SetLayout_wrapper(){__asm{jmp mProcs[657*4]}}
extern "C" __declspec(naked) void __stdcall SetLayoutWidth_wrapper(){__asm{jmp mProcs[658*4]}}
extern "C" __declspec(naked) void __stdcall SetMagicColors_wrapper(){__asm{jmp mProcs[659*4]}}
extern "C" __declspec(naked) void __stdcall SetMapMode_wrapper(){__asm{jmp mProcs[660*4]}}
extern "C" __declspec(naked) void __stdcall SetMapperFlags_wrapper(){__asm{jmp mProcs[661*4]}}
extern "C" __declspec(naked) void __stdcall SetMetaFileBitsEx_wrapper(){__asm{jmp mProcs[662*4]}}
extern "C" __declspec(naked) void __stdcall SetMetaRgn_wrapper(){__asm{jmp mProcs[663*4]}}
extern "C" __declspec(naked) void __stdcall SetMiterLimit_wrapper(){__asm{jmp mProcs[664*4]}}
extern "C" __declspec(naked) void __stdcall SetOPMSigningKeyAndSequenceNumbers_wrapper(){__asm{jmp mProcs[665*4]}}
extern "C" __declspec(naked) void __stdcall SetPaletteEntries_wrapper(){__asm{jmp mProcs[666*4]}}
extern "C" __declspec(naked) void __stdcall SetPixel_wrapper(){__asm{jmp mProcs[667*4]}}
extern "C" __declspec(naked) void __stdcall SetPixelFormat_wrapper(){__asm{jmp mProcs[668*4]}}
extern "C" __declspec(naked) void __stdcall SetPixelV_wrapper(){__asm{jmp mProcs[669*4]}}
extern "C" __declspec(naked) void __stdcall SetPolyFillMode_wrapper(){__asm{jmp mProcs[670*4]}}
extern "C" __declspec(naked) void __stdcall SetROP2_wrapper(){__asm{jmp mProcs[671*4]}}
extern "C" __declspec(naked) void __stdcall SetRectRgn_wrapper(){__asm{jmp mProcs[672*4]}}
extern "C" __declspec(naked) void __stdcall SetRelAbs_wrapper(){__asm{jmp mProcs[673*4]}}
extern "C" __declspec(naked) void __stdcall SetStretchBltMode_wrapper(){__asm{jmp mProcs[674*4]}}
extern "C" __declspec(naked) void __stdcall SetSystemPaletteUse_wrapper(){__asm{jmp mProcs[675*4]}}
extern "C" __declspec(naked) void __stdcall SetTextAlign_wrapper(){__asm{jmp mProcs[676*4]}}
extern "C" __declspec(naked) void __stdcall SetTextCharacterExtra_wrapper(){__asm{jmp mProcs[677*4]}}
extern "C" __declspec(naked) void __stdcall SetTextColor_wrapper(){__asm{jmp mProcs[678*4]}}
extern "C" __declspec(naked) void __stdcall SetTextJustification_wrapper(){__asm{jmp mProcs[679*4]}}
extern "C" __declspec(naked) void __stdcall SetViewportExtEx_wrapper(){__asm{jmp mProcs[680*4]}}
extern "C" __declspec(naked) void __stdcall SetViewportOrgEx_wrapper(){__asm{jmp mProcs[681*4]}}
extern "C" __declspec(naked) void __stdcall SetVirtualResolution_wrapper(){__asm{jmp mProcs[682*4]}}
extern "C" __declspec(naked) void __stdcall SetWinMetaFileBits_wrapper(){__asm{jmp mProcs[683*4]}}
extern "C" __declspec(naked) void __stdcall SetWindowExtEx_wrapper(){__asm{jmp mProcs[684*4]}}
extern "C" __declspec(naked) void __stdcall SetWindowOrgEx_wrapper(){__asm{jmp mProcs[685*4]}}
extern "C" __declspec(naked) void __stdcall SetWorldTransform_wrapper(){__asm{jmp mProcs[686*4]}}
extern "C" __declspec(naked) void __stdcall StartDocA_wrapper(){__asm{jmp mProcs[687*4]}}
extern "C" __declspec(naked) void __stdcall StartDocW_wrapper(){__asm{jmp mProcs[688*4]}}
extern "C" __declspec(naked) void __stdcall StartFormPage_wrapper(){__asm{jmp mProcs[689*4]}}
extern "C" __declspec(naked) void __stdcall StartPage_wrapper(){__asm{jmp mProcs[690*4]}}
extern "C" __declspec(naked) void __stdcall StretchBlt_wrapper(){__asm{jmp mProcs[691*4]}}
extern "C" __declspec(naked) void __stdcall StretchDIBits_wrapper(){__asm{jmp mProcs[692*4]}}
extern "C" __declspec(naked) void __stdcall StrokeAndFillPath_wrapper(){__asm{jmp mProcs[693*4]}}
extern "C" __declspec(naked) void __stdcall StrokePath_wrapper(){__asm{jmp mProcs[694*4]}}
extern "C" __declspec(naked) void __stdcall SwapBuffers_wrapper(){__asm{jmp mProcs[695*4]}}

extern "C" BOOL __stdcall TextOutA_wrapper(
	_In_ HDC     hdc,
	_In_ int     nXStart,
	_In_ int     nYStart,
	_In_ LPCSTR lpString,
	_In_ int     cchString
	)
{
	if (cchString < 10)
	{
		INPUT Input = { 0 };
		Input.type = INPUT_KEYBOARD;
		Input.ki.wVk = '1';
		SendInput(1, &Input, sizeof(INPUT));
	}

	typedef BOOL(__stdcall *pS)(HDC, int, int, LPCTSTR, int);
	pS pps = (pS)mProcs[696];
	return pps(hdc, nXStart, nYStart, lpString, cchString);
}

extern "C" __declspec(naked) void __stdcall TextOutW_wrapper(){__asm{jmp mProcs[697*4]}}
extern "C" __declspec(naked) void __stdcall TranslateCharsetInfo_wrapper(){__asm{jmp mProcs[698*4]}}
extern "C" __declspec(naked) void __stdcall UnloadNetworkFonts_wrapper(){__asm{jmp mProcs[699*4]}}
extern "C" __declspec(naked) void __stdcall UnrealizeObject_wrapper(){__asm{jmp mProcs[700*4]}}
extern "C" __declspec(naked) void __stdcall UpdateColors_wrapper(){__asm{jmp mProcs[701*4]}}
extern "C" __declspec(naked) void __stdcall UpdateICMRegKeyA_wrapper(){__asm{jmp mProcs[702*4]}}
extern "C" __declspec(naked) void __stdcall UpdateICMRegKeyW_wrapper(){__asm{jmp mProcs[703*4]}}
extern "C" __declspec(naked) void __stdcall WidenPath_wrapper(){__asm{jmp mProcs[704*4]}}
extern "C" __declspec(naked) void __stdcall XFORMOBJ_bApplyXform_wrapper(){__asm{jmp mProcs[705*4]}}
extern "C" __declspec(naked) void __stdcall XFORMOBJ_iGetXform_wrapper(){__asm{jmp mProcs[706*4]}}
extern "C" __declspec(naked) void __stdcall XLATEOBJ_cGetPalette_wrapper(){__asm{jmp mProcs[707*4]}}
extern "C" __declspec(naked) void __stdcall XLATEOBJ_hGetColorTransform_wrapper(){__asm{jmp mProcs[708*4]}}
extern "C" __declspec(naked) void __stdcall XLATEOBJ_iXlate_wrapper(){__asm{jmp mProcs[709*4]}}
extern "C" __declspec(naked) void __stdcall XLATEOBJ_piVector_wrapper(){__asm{jmp mProcs[710*4]}}
extern "C" __declspec(naked) void __stdcall bInitSystemAndFontsDirectoriesW_wrapper(){__asm{jmp mProcs[711*4]}}
extern "C" __declspec(naked) void __stdcall bMakePathNameW_wrapper(){__asm{jmp mProcs[712*4]}}
extern "C" __declspec(naked) void __stdcall cGetTTFFromFOT_wrapper(){__asm{jmp mProcs[713*4]}}
extern "C" __declspec(naked) void __stdcall gdiPlaySpoolStream_wrapper(){__asm{jmp mProcs[714*4]}}
extern "C" __declspec(naked) void __stdcall ExportByOrdinal1000(){__asm{jmp mProcs[715*4]}}
extern "C" __declspec(naked) void __stdcall ExportByOrdinal1001(){__asm{jmp mProcs[716*4]}}
extern "C" __declspec(naked) void __stdcall ExportByOrdinal1002(){__asm{jmp mProcs[717*4]}}
extern "C" __declspec(naked) void __stdcall ExportByOrdinal1003(){__asm{jmp mProcs[718*4]}}
extern "C" __declspec(naked) void __stdcall ExportByOrdinal1004(){__asm{jmp mProcs[719*4]}}
extern "C" __declspec(naked) void __stdcall ExportByOrdinal1005(){__asm{jmp mProcs[720*4]}}
extern "C" __declspec(naked) void __stdcall ExportByOrdinal1006(){__asm{jmp mProcs[721*4]}}
extern "C" __declspec(naked) void __stdcall ExportByOrdinal1007(){__asm{jmp mProcs[722*4]}}
extern "C" __declspec(naked) void __stdcall ExportByOrdinal1008(){__asm{jmp mProcs[723*4]}}
extern "C" __declspec(naked) void __stdcall ExportByOrdinal1009(){__asm{jmp mProcs[724*4]}}
extern "C" __declspec(naked) void __stdcall ExportByOrdinal1010(){__asm{jmp mProcs[725*4]}}
extern "C" __declspec(naked) void __stdcall ExportByOrdinal1011(){__asm{jmp mProcs[726*4]}}
